# Number of days of inactivity before a PR becomes stale.
daysUntilStale: 60
# Number of days of inactivity before a stale PR is closed.
daysUntilClose: 30

# Limit to only `pulls`.
only: pulls

# Issues or Pull Requests with these labels will never be considered stale.
# Set to `[]` to disable.
exemptLabels:
  - no-mergify
  - do-not-merge

# Comment to post when marking an issue as stale. Set to `false` to disable.
markComment: >
  This pull request has been automatically marked as stale because it has not
  had recent activity (60 days of inactivity).

  It will be closed in 30 days if no further activity occurs.

  Thank you for your contribution!

# Comment to post when closing a stale issue. Set to `false` to disable.
closeComment: >
  This pull request has been automatically closed because there has
  been no activity for 90 days.

  Please feel free to reopen it (or open a new one) if the proposed
  change is still appropriate.

  Thank you for your contribution!
