run:
  timeout: 6m
  build-tags:
    - integration

linters:
  enable:
    - forcetypeassert
    - errcheck

issues:
  max-same-issues: 50
  exclude-rules:
    - path: ".*\\.pb\\.go$"
      linters:
        - all
    - path: "pkg/assembler/generated/.*"
      linters:
        - all
    - path: "resolvers/schema\\.resolvers\\.go"
      linters:
        - all
    - path: "_test\\.go"
      linters:
        - forcetypeassert
    - path: "pkg/assembler/backends/neo4j"
      linters:
        - unused
        - forcetypeassert
    - linters:
        - errcheck
      text: "Error return value of .*(Close|Setenv) is not checked"
