run:
  timeout: 2m
  skip-files:
    - ".*\\.pb\\.go$"
    - "pkg/assembler/generated/.*"
    - "resolvers/schema\\.resolvers\\.go"
linters:
  enable:
    - wrapcheck
issues:
  # Exclude previously existing issues from the report
  new: true
  new-from-rev: HEAD
