apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: guac-task
spec:
  description: >-
    This Task is used to call guac commands to interact with graphDB.
  params:
  - name: image-ref
    description: image reference
  - name: guac-image
    type: string
    default: ppatel1989/guacone-bbf258055f2020a39f05cfa863255f6e:latest@sha256:164ad81517d682375cb9af682e1d488b87dcc6b77e257d3502a7092fd2d31904
  - name: gdbuser
    description: neo4j user
  - name: gdpassword
    description: neo4j password
  - name: gdbaddr
    description: guac address to neo4j db
    default: "neo4j://localhost:7687"
  workspaces:
  - name: source
    description: A workspace where files will be uploaded from.
  steps:
  - name: guacone
    image: "$(params.guac-image)"
    args:
        - image
        - --gdbuser
        - $GDBUSER
        - --gdbpass
        - $GDBPASS
        - --gdbaddr
        - $GDBADDR
        - $(params.image-ref)
    env:
    - name: GDBUSER
      value: "$(params.gdbuser)"
    - name: GDBPASS
      value: "$(params.gdpassword)"
    - name: GDBADDR
      value: "$(params.gdbaddr)"
