// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"github.com/99designs/gqlgen/graphql"
)

func (_m *Artifact) Occurrences(ctx context.Context) (result []*Occurrence, err error) {
	if fc := graphql.GetFieldContext(ctx); fc != nil && fc.Field.Alias != "" {
		result, err = _m.NamedOccurrences(graphql.GetFieldContext(ctx).Field.Alias)
	} else {
		result, err = _m.Edges.OccurrencesOrErr()
	}
	if IsNotLoaded(err) {
		result, err = _m.QueryOccurrences().All(ctx)
	}
	return result, err
}

func (_m *Artifact) Sbom(ctx context.Context) (result []*BillOfMaterials, err error) {
	if fc := graphql.GetFieldContext(ctx); fc != nil && fc.Field.Alias != "" {
		result, err = _m.NamedSbom(graphql.GetFieldContext(ctx).Field.Alias)
	} else {
		result, err = _m.Edges.SbomOrErr()
	}
	if IsNotLoaded(err) {
		result, err = _m.QuerySbom().All(ctx)
	}
	return result, err
}

func (_m *Artifact) Attestations(ctx context.Context) (result []*SLSAAttestation, err error) {
	if fc := graphql.GetFieldContext(ctx); fc != nil && fc.Field.Alias != "" {
		result, err = _m.NamedAttestations(graphql.GetFieldContext(ctx).Field.Alias)
	} else {
		result, err = _m.Edges.AttestationsOrErr()
	}
	if IsNotLoaded(err) {
		result, err = _m.QueryAttestations().All(ctx)
	}
	return result, err
}

func (_m *Artifact) AttestationsSubject(ctx context.Context) (result []*SLSAAttestation, err error) {
	if fc := graphql.GetFieldContext(ctx); fc != nil && fc.Field.Alias != "" {
		result, err = _m.NamedAttestationsSubject(graphql.GetFieldContext(ctx).Field.Alias)
	} else {
		result, err = _m.Edges.AttestationsSubjectOrErr()
	}
	if IsNotLoaded(err) {
		result, err = _m.QueryAttestationsSubject().All(ctx)
	}
	return result, err
}

func (_m *Artifact) HashEqualArtA(ctx context.Context) (result []*HashEqual, err error) {
	if fc := graphql.GetFieldContext(ctx); fc != nil && fc.Field.Alias != "" {
		result, err = _m.NamedHashEqualArtA(graphql.GetFieldContext(ctx).Field.Alias)
	} else {
		result, err = _m.Edges.HashEqualArtAOrErr()
	}
	if IsNotLoaded(err) {
		result, err = _m.QueryHashEqualArtA().All(ctx)
	}
	return result, err
}

func (_m *Artifact) HashEqualArtB(ctx context.Context) (result []*HashEqual, err error) {
	if fc := graphql.GetFieldContext(ctx); fc != nil && fc.Field.Alias != "" {
		result, err = _m.NamedHashEqualArtB(graphql.GetFieldContext(ctx).Field.Alias)
	} else {
		result, err = _m.Edges.HashEqualArtBOrErr()
	}
	if IsNotLoaded(err) {
		result, err = _m.QueryHashEqualArtB().All(ctx)
	}
	return result, err
}

func (_m *Artifact) Vex(ctx context.Context) (result []*CertifyVex, err error) {
	if fc := graphql.GetFieldContext(ctx); fc != nil && fc.Field.Alias != "" {
		result, err = _m.NamedVex(graphql.GetFieldContext(ctx).Field.Alias)
	} else {
		result, err = _m.Edges.VexOrErr()
	}
	if IsNotLoaded(err) {
		result, err = _m.QueryVex().All(ctx)
	}
	return result, err
}

func (_m *Artifact) Certification(ctx context.Context) (result []*Certification, err error) {
	if fc := graphql.GetFieldContext(ctx); fc != nil && fc.Field.Alias != "" {
		result, err = _m.NamedCertification(graphql.GetFieldContext(ctx).Field.Alias)
	} else {
		result, err = _m.Edges.CertificationOrErr()
	}
	if IsNotLoaded(err) {
		result, err = _m.QueryCertification().All(ctx)
	}
	return result, err
}

func (_m *Artifact) Metadata(ctx context.Context) (result []*HasMetadata, err error) {
	if fc := graphql.GetFieldContext(ctx); fc != nil && fc.Field.Alias != "" {
		result, err = _m.NamedMetadata(graphql.GetFieldContext(ctx).Field.Alias)
	} else {
		result, err = _m.Edges.MetadataOrErr()
	}
	if IsNotLoaded(err) {
		result, err = _m.QueryMetadata().All(ctx)
	}
	return result, err
}

func (_m *Artifact) Poc(ctx context.Context) (result []*PointOfContact, err error) {
	if fc := graphql.GetFieldContext(ctx); fc != nil && fc.Field.Alias != "" {
		result, err = _m.NamedPoc(graphql.GetFieldContext(ctx).Field.Alias)
	} else {
		result, err = _m.Edges.PocOrErr()
	}
	if IsNotLoaded(err) {
		result, err = _m.QueryPoc().All(ctx)
	}
	return result, err
}

func (_m *Artifact) IncludedInSboms(ctx context.Context) (result []*BillOfMaterials, err error) {
	if fc := graphql.GetFieldContext(ctx); fc != nil && fc.Field.Alias != "" {
		result, err = _m.NamedIncludedInSboms(graphql.GetFieldContext(ctx).Field.Alias)
	} else {
		result, err = _m.Edges.IncludedInSbomsOrErr()
	}
	if IsNotLoaded(err) {
		result, err = _m.QueryIncludedInSboms().All(ctx)
	}
	return result, err
}

func (_m *BillOfMaterials) Package(ctx context.Context) (*PackageVersion, error) {
	result, err := _m.Edges.PackageOrErr()
	if IsNotLoaded(err) {
		result, err = _m.QueryPackage().Only(ctx)
	}
	return result, MaskNotFound(err)
}

func (_m *BillOfMaterials) Artifact(ctx context.Context) (*Artifact, error) {
	result, err := _m.Edges.ArtifactOrErr()
	if IsNotLoaded(err) {
		result, err = _m.QueryArtifact().Only(ctx)
	}
	return result, MaskNotFound(err)
}

func (_m *BillOfMaterials) IncludedSoftwarePackages(ctx context.Context) (result []*PackageVersion, err error) {
	if fc := graphql.GetFieldContext(ctx); fc != nil && fc.Field.Alias != "" {
		result, err = _m.NamedIncludedSoftwarePackages(graphql.GetFieldContext(ctx).Field.Alias)
	} else {
		result, err = _m.Edges.IncludedSoftwarePackagesOrErr()
	}
	if IsNotLoaded(err) {
		result, err = _m.QueryIncludedSoftwarePackages().All(ctx)
	}
	return result, err
}

func (_m *BillOfMaterials) IncludedSoftwareArtifacts(ctx context.Context) (result []*Artifact, err error) {
	if fc := graphql.GetFieldContext(ctx); fc != nil && fc.Field.Alias != "" {
		result, err = _m.NamedIncludedSoftwareArtifacts(graphql.GetFieldContext(ctx).Field.Alias)
	} else {
		result, err = _m.Edges.IncludedSoftwareArtifactsOrErr()
	}
	if IsNotLoaded(err) {
		result, err = _m.QueryIncludedSoftwareArtifacts().All(ctx)
	}
	return result, err
}

func (_m *BillOfMaterials) IncludedDependencies(ctx context.Context) (result []*Dependency, err error) {
	if fc := graphql.GetFieldContext(ctx); fc != nil && fc.Field.Alias != "" {
		result, err = _m.NamedIncludedDependencies(graphql.GetFieldContext(ctx).Field.Alias)
	} else {
		result, err = _m.Edges.IncludedDependenciesOrErr()
	}
	if IsNotLoaded(err) {
		result, err = _m.QueryIncludedDependencies().All(ctx)
	}
	return result, err
}

func (_m *BillOfMaterials) IncludedOccurrences(ctx context.Context) (result []*Occurrence, err error) {
	if fc := graphql.GetFieldContext(ctx); fc != nil && fc.Field.Alias != "" {
		result, err = _m.NamedIncludedOccurrences(graphql.GetFieldContext(ctx).Field.Alias)
	} else {
		result, err = _m.Edges.IncludedOccurrencesOrErr()
	}
	if IsNotLoaded(err) {
		result, err = _m.QueryIncludedOccurrences().All(ctx)
	}
	return result, err
}

func (_m *Builder) SlsaAttestations(ctx context.Context) (result []*SLSAAttestation, err error) {
	if fc := graphql.GetFieldContext(ctx); fc != nil && fc.Field.Alias != "" {
		result, err = _m.NamedSlsaAttestations(graphql.GetFieldContext(ctx).Field.Alias)
	} else {
		result, err = _m.Edges.SlsaAttestationsOrErr()
	}
	if IsNotLoaded(err) {
		result, err = _m.QuerySlsaAttestations().All(ctx)
	}
	return result, err
}

func (_m *Certification) Source(ctx context.Context) (*SourceName, error) {
	result, err := _m.Edges.SourceOrErr()
	if IsNotLoaded(err) {
		result, err = _m.QuerySource().Only(ctx)
	}
	return result, MaskNotFound(err)
}

func (_m *Certification) PackageVersion(ctx context.Context) (*PackageVersion, error) {
	result, err := _m.Edges.PackageVersionOrErr()
	if IsNotLoaded(err) {
		result, err = _m.QueryPackageVersion().Only(ctx)
	}
	return result, MaskNotFound(err)
}

func (_m *Certification) AllVersions(ctx context.Context) (*PackageName, error) {
	result, err := _m.Edges.AllVersionsOrErr()
	if IsNotLoaded(err) {
		result, err = _m.QueryAllVersions().Only(ctx)
	}
	return result, MaskNotFound(err)
}

func (_m *Certification) Artifact(ctx context.Context) (*Artifact, error) {
	result, err := _m.Edges.ArtifactOrErr()
	if IsNotLoaded(err) {
		result, err = _m.QueryArtifact().Only(ctx)
	}
	return result, MaskNotFound(err)
}

func (_m *CertifyLegal) Package(ctx context.Context) (*PackageVersion, error) {
	result, err := _m.Edges.PackageOrErr()
	if IsNotLoaded(err) {
		result, err = _m.QueryPackage().Only(ctx)
	}
	return result, MaskNotFound(err)
}

func (_m *CertifyLegal) Source(ctx context.Context) (*SourceName, error) {
	result, err := _m.Edges.SourceOrErr()
	if IsNotLoaded(err) {
		result, err = _m.QuerySource().Only(ctx)
	}
	return result, MaskNotFound(err)
}

func (_m *CertifyLegal) DeclaredLicenses(ctx context.Context) (result []*License, err error) {
	if fc := graphql.GetFieldContext(ctx); fc != nil && fc.Field.Alias != "" {
		result, err = _m.NamedDeclaredLicenses(graphql.GetFieldContext(ctx).Field.Alias)
	} else {
		result, err = _m.Edges.DeclaredLicensesOrErr()
	}
	if IsNotLoaded(err) {
		result, err = _m.QueryDeclaredLicenses().All(ctx)
	}
	return result, err
}

func (_m *CertifyLegal) DiscoveredLicenses(ctx context.Context) (result []*License, err error) {
	if fc := graphql.GetFieldContext(ctx); fc != nil && fc.Field.Alias != "" {
		result, err = _m.NamedDiscoveredLicenses(graphql.GetFieldContext(ctx).Field.Alias)
	} else {
		result, err = _m.Edges.DiscoveredLicensesOrErr()
	}
	if IsNotLoaded(err) {
		result, err = _m.QueryDiscoveredLicenses().All(ctx)
	}
	return result, err
}

func (_m *CertifyScorecard) Source(ctx context.Context) (*SourceName, error) {
	result, err := _m.Edges.SourceOrErr()
	if IsNotLoaded(err) {
		result, err = _m.QuerySource().Only(ctx)
	}
	return result, err
}

func (_m *CertifyVex) Package(ctx context.Context) (*PackageVersion, error) {
	result, err := _m.Edges.PackageOrErr()
	if IsNotLoaded(err) {
		result, err = _m.QueryPackage().Only(ctx)
	}
	return result, MaskNotFound(err)
}

func (_m *CertifyVex) Artifact(ctx context.Context) (*Artifact, error) {
	result, err := _m.Edges.ArtifactOrErr()
	if IsNotLoaded(err) {
		result, err = _m.QueryArtifact().Only(ctx)
	}
	return result, MaskNotFound(err)
}

func (_m *CertifyVex) Vulnerability(ctx context.Context) (*VulnerabilityID, error) {
	result, err := _m.Edges.VulnerabilityOrErr()
	if IsNotLoaded(err) {
		result, err = _m.QueryVulnerability().Only(ctx)
	}
	return result, err
}

func (_m *CertifyVuln) Vulnerability(ctx context.Context) (*VulnerabilityID, error) {
	result, err := _m.Edges.VulnerabilityOrErr()
	if IsNotLoaded(err) {
		result, err = _m.QueryVulnerability().Only(ctx)
	}
	return result, err
}

func (_m *CertifyVuln) Package(ctx context.Context) (*PackageVersion, error) {
	result, err := _m.Edges.PackageOrErr()
	if IsNotLoaded(err) {
		result, err = _m.QueryPackage().Only(ctx)
	}
	return result, err
}

func (_m *Dependency) Package(ctx context.Context) (*PackageVersion, error) {
	result, err := _m.Edges.PackageOrErr()
	if IsNotLoaded(err) {
		result, err = _m.QueryPackage().Only(ctx)
	}
	return result, err
}

func (_m *Dependency) DependentPackageVersion(ctx context.Context) (*PackageVersion, error) {
	result, err := _m.Edges.DependentPackageVersionOrErr()
	if IsNotLoaded(err) {
		result, err = _m.QueryDependentPackageVersion().Only(ctx)
	}
	return result, err
}

func (_m *Dependency) IncludedInSboms(ctx context.Context) (result []*BillOfMaterials, err error) {
	if fc := graphql.GetFieldContext(ctx); fc != nil && fc.Field.Alias != "" {
		result, err = _m.NamedIncludedInSboms(graphql.GetFieldContext(ctx).Field.Alias)
	} else {
		result, err = _m.Edges.IncludedInSbomsOrErr()
	}
	if IsNotLoaded(err) {
		result, err = _m.QueryIncludedInSboms().All(ctx)
	}
	return result, err
}

func (_m *HasMetadata) Source(ctx context.Context) (*SourceName, error) {
	result, err := _m.Edges.SourceOrErr()
	if IsNotLoaded(err) {
		result, err = _m.QuerySource().Only(ctx)
	}
	return result, MaskNotFound(err)
}

func (_m *HasMetadata) PackageVersion(ctx context.Context) (*PackageVersion, error) {
	result, err := _m.Edges.PackageVersionOrErr()
	if IsNotLoaded(err) {
		result, err = _m.QueryPackageVersion().Only(ctx)
	}
	return result, MaskNotFound(err)
}

func (_m *HasMetadata) AllVersions(ctx context.Context) (*PackageName, error) {
	result, err := _m.Edges.AllVersionsOrErr()
	if IsNotLoaded(err) {
		result, err = _m.QueryAllVersions().Only(ctx)
	}
	return result, MaskNotFound(err)
}

func (_m *HasMetadata) Artifact(ctx context.Context) (*Artifact, error) {
	result, err := _m.Edges.ArtifactOrErr()
	if IsNotLoaded(err) {
		result, err = _m.QueryArtifact().Only(ctx)
	}
	return result, MaskNotFound(err)
}

func (_m *HasSourceAt) PackageVersion(ctx context.Context) (*PackageVersion, error) {
	result, err := _m.Edges.PackageVersionOrErr()
	if IsNotLoaded(err) {
		result, err = _m.QueryPackageVersion().Only(ctx)
	}
	return result, MaskNotFound(err)
}

func (_m *HasSourceAt) AllVersions(ctx context.Context) (*PackageName, error) {
	result, err := _m.Edges.AllVersionsOrErr()
	if IsNotLoaded(err) {
		result, err = _m.QueryAllVersions().Only(ctx)
	}
	return result, MaskNotFound(err)
}

func (_m *HasSourceAt) Source(ctx context.Context) (*SourceName, error) {
	result, err := _m.Edges.SourceOrErr()
	if IsNotLoaded(err) {
		result, err = _m.QuerySource().Only(ctx)
	}
	return result, err
}

func (_m *HashEqual) ArtifactA(ctx context.Context) (*Artifact, error) {
	result, err := _m.Edges.ArtifactAOrErr()
	if IsNotLoaded(err) {
		result, err = _m.QueryArtifactA().Only(ctx)
	}
	return result, err
}

func (_m *HashEqual) ArtifactB(ctx context.Context) (*Artifact, error) {
	result, err := _m.Edges.ArtifactBOrErr()
	if IsNotLoaded(err) {
		result, err = _m.QueryArtifactB().Only(ctx)
	}
	return result, err
}

func (_m *License) DeclaredInCertifyLegals(ctx context.Context) (result []*CertifyLegal, err error) {
	if fc := graphql.GetFieldContext(ctx); fc != nil && fc.Field.Alias != "" {
		result, err = _m.NamedDeclaredInCertifyLegals(graphql.GetFieldContext(ctx).Field.Alias)
	} else {
		result, err = _m.Edges.DeclaredInCertifyLegalsOrErr()
	}
	if IsNotLoaded(err) {
		result, err = _m.QueryDeclaredInCertifyLegals().All(ctx)
	}
	return result, err
}

func (_m *License) DiscoveredInCertifyLegals(ctx context.Context) (result []*CertifyLegal, err error) {
	if fc := graphql.GetFieldContext(ctx); fc != nil && fc.Field.Alias != "" {
		result, err = _m.NamedDiscoveredInCertifyLegals(graphql.GetFieldContext(ctx).Field.Alias)
	} else {
		result, err = _m.Edges.DiscoveredInCertifyLegalsOrErr()
	}
	if IsNotLoaded(err) {
		result, err = _m.QueryDiscoveredInCertifyLegals().All(ctx)
	}
	return result, err
}

func (_m *Occurrence) Artifact(ctx context.Context) (*Artifact, error) {
	result, err := _m.Edges.ArtifactOrErr()
	if IsNotLoaded(err) {
		result, err = _m.QueryArtifact().Only(ctx)
	}
	return result, err
}

func (_m *Occurrence) Package(ctx context.Context) (*PackageVersion, error) {
	result, err := _m.Edges.PackageOrErr()
	if IsNotLoaded(err) {
		result, err = _m.QueryPackage().Only(ctx)
	}
	return result, MaskNotFound(err)
}

func (_m *Occurrence) Source(ctx context.Context) (*SourceName, error) {
	result, err := _m.Edges.SourceOrErr()
	if IsNotLoaded(err) {
		result, err = _m.QuerySource().Only(ctx)
	}
	return result, MaskNotFound(err)
}

func (_m *Occurrence) IncludedInSboms(ctx context.Context) (result []*BillOfMaterials, err error) {
	if fc := graphql.GetFieldContext(ctx); fc != nil && fc.Field.Alias != "" {
		result, err = _m.NamedIncludedInSboms(graphql.GetFieldContext(ctx).Field.Alias)
	} else {
		result, err = _m.Edges.IncludedInSbomsOrErr()
	}
	if IsNotLoaded(err) {
		result, err = _m.QueryIncludedInSboms().All(ctx)
	}
	return result, err
}

func (_m *PackageName) Versions(ctx context.Context) (result []*PackageVersion, err error) {
	if fc := graphql.GetFieldContext(ctx); fc != nil && fc.Field.Alias != "" {
		result, err = _m.NamedVersions(graphql.GetFieldContext(ctx).Field.Alias)
	} else {
		result, err = _m.Edges.VersionsOrErr()
	}
	if IsNotLoaded(err) {
		result, err = _m.QueryVersions().All(ctx)
	}
	return result, err
}

func (_m *PackageName) HasSourceAt(ctx context.Context) (result []*HasSourceAt, err error) {
	if fc := graphql.GetFieldContext(ctx); fc != nil && fc.Field.Alias != "" {
		result, err = _m.NamedHasSourceAt(graphql.GetFieldContext(ctx).Field.Alias)
	} else {
		result, err = _m.Edges.HasSourceAtOrErr()
	}
	if IsNotLoaded(err) {
		result, err = _m.QueryHasSourceAt().All(ctx)
	}
	return result, err
}

func (_m *PackageName) Certification(ctx context.Context) (result []*Certification, err error) {
	if fc := graphql.GetFieldContext(ctx); fc != nil && fc.Field.Alias != "" {
		result, err = _m.NamedCertification(graphql.GetFieldContext(ctx).Field.Alias)
	} else {
		result, err = _m.Edges.CertificationOrErr()
	}
	if IsNotLoaded(err) {
		result, err = _m.QueryCertification().All(ctx)
	}
	return result, err
}

func (_m *PackageName) Metadata(ctx context.Context) (result []*HasMetadata, err error) {
	if fc := graphql.GetFieldContext(ctx); fc != nil && fc.Field.Alias != "" {
		result, err = _m.NamedMetadata(graphql.GetFieldContext(ctx).Field.Alias)
	} else {
		result, err = _m.Edges.MetadataOrErr()
	}
	if IsNotLoaded(err) {
		result, err = _m.QueryMetadata().All(ctx)
	}
	return result, err
}

func (_m *PackageName) Poc(ctx context.Context) (result []*PointOfContact, err error) {
	if fc := graphql.GetFieldContext(ctx); fc != nil && fc.Field.Alias != "" {
		result, err = _m.NamedPoc(graphql.GetFieldContext(ctx).Field.Alias)
	} else {
		result, err = _m.Edges.PocOrErr()
	}
	if IsNotLoaded(err) {
		result, err = _m.QueryPoc().All(ctx)
	}
	return result, err
}

func (_m *PackageVersion) Name(ctx context.Context) (*PackageName, error) {
	result, err := _m.Edges.NameOrErr()
	if IsNotLoaded(err) {
		result, err = _m.QueryName().Only(ctx)
	}
	return result, err
}

func (_m *PackageVersion) Occurrences(ctx context.Context) (result []*Occurrence, err error) {
	if fc := graphql.GetFieldContext(ctx); fc != nil && fc.Field.Alias != "" {
		result, err = _m.NamedOccurrences(graphql.GetFieldContext(ctx).Field.Alias)
	} else {
		result, err = _m.Edges.OccurrencesOrErr()
	}
	if IsNotLoaded(err) {
		result, err = _m.QueryOccurrences().All(ctx)
	}
	return result, err
}

func (_m *PackageVersion) Sbom(ctx context.Context) (result []*BillOfMaterials, err error) {
	if fc := graphql.GetFieldContext(ctx); fc != nil && fc.Field.Alias != "" {
		result, err = _m.NamedSbom(graphql.GetFieldContext(ctx).Field.Alias)
	} else {
		result, err = _m.Edges.SbomOrErr()
	}
	if IsNotLoaded(err) {
		result, err = _m.QuerySbom().All(ctx)
	}
	return result, err
}

func (_m *PackageVersion) Vuln(ctx context.Context) (result []*CertifyVuln, err error) {
	if fc := graphql.GetFieldContext(ctx); fc != nil && fc.Field.Alias != "" {
		result, err = _m.NamedVuln(graphql.GetFieldContext(ctx).Field.Alias)
	} else {
		result, err = _m.Edges.VulnOrErr()
	}
	if IsNotLoaded(err) {
		result, err = _m.QueryVuln().All(ctx)
	}
	return result, err
}

func (_m *PackageVersion) Vex(ctx context.Context) (result []*CertifyVex, err error) {
	if fc := graphql.GetFieldContext(ctx); fc != nil && fc.Field.Alias != "" {
		result, err = _m.NamedVex(graphql.GetFieldContext(ctx).Field.Alias)
	} else {
		result, err = _m.Edges.VexOrErr()
	}
	if IsNotLoaded(err) {
		result, err = _m.QueryVex().All(ctx)
	}
	return result, err
}

func (_m *PackageVersion) HasSourceAt(ctx context.Context) (result []*HasSourceAt, err error) {
	if fc := graphql.GetFieldContext(ctx); fc != nil && fc.Field.Alias != "" {
		result, err = _m.NamedHasSourceAt(graphql.GetFieldContext(ctx).Field.Alias)
	} else {
		result, err = _m.Edges.HasSourceAtOrErr()
	}
	if IsNotLoaded(err) {
		result, err = _m.QueryHasSourceAt().All(ctx)
	}
	return result, err
}

func (_m *PackageVersion) Certification(ctx context.Context) (result []*Certification, err error) {
	if fc := graphql.GetFieldContext(ctx); fc != nil && fc.Field.Alias != "" {
		result, err = _m.NamedCertification(graphql.GetFieldContext(ctx).Field.Alias)
	} else {
		result, err = _m.Edges.CertificationOrErr()
	}
	if IsNotLoaded(err) {
		result, err = _m.QueryCertification().All(ctx)
	}
	return result, err
}

func (_m *PackageVersion) Metadata(ctx context.Context) (result []*HasMetadata, err error) {
	if fc := graphql.GetFieldContext(ctx); fc != nil && fc.Field.Alias != "" {
		result, err = _m.NamedMetadata(graphql.GetFieldContext(ctx).Field.Alias)
	} else {
		result, err = _m.Edges.MetadataOrErr()
	}
	if IsNotLoaded(err) {
		result, err = _m.QueryMetadata().All(ctx)
	}
	return result, err
}

func (_m *PackageVersion) Dependency(ctx context.Context) (result []*Dependency, err error) {
	if fc := graphql.GetFieldContext(ctx); fc != nil && fc.Field.Alias != "" {
		result, err = _m.NamedDependency(graphql.GetFieldContext(ctx).Field.Alias)
	} else {
		result, err = _m.Edges.DependencyOrErr()
	}
	if IsNotLoaded(err) {
		result, err = _m.QueryDependency().All(ctx)
	}
	return result, err
}

func (_m *PackageVersion) DependencySubject(ctx context.Context) (result []*Dependency, err error) {
	if fc := graphql.GetFieldContext(ctx); fc != nil && fc.Field.Alias != "" {
		result, err = _m.NamedDependencySubject(graphql.GetFieldContext(ctx).Field.Alias)
	} else {
		result, err = _m.Edges.DependencySubjectOrErr()
	}
	if IsNotLoaded(err) {
		result, err = _m.QueryDependencySubject().All(ctx)
	}
	return result, err
}

func (_m *PackageVersion) IncludedInSboms(ctx context.Context) (result []*BillOfMaterials, err error) {
	if fc := graphql.GetFieldContext(ctx); fc != nil && fc.Field.Alias != "" {
		result, err = _m.NamedIncludedInSboms(graphql.GetFieldContext(ctx).Field.Alias)
	} else {
		result, err = _m.Edges.IncludedInSbomsOrErr()
	}
	if IsNotLoaded(err) {
		result, err = _m.QueryIncludedInSboms().All(ctx)
	}
	return result, err
}

func (_m *PackageVersion) PkgEqualPkgA(ctx context.Context) (result []*PkgEqual, err error) {
	if fc := graphql.GetFieldContext(ctx); fc != nil && fc.Field.Alias != "" {
		result, err = _m.NamedPkgEqualPkgA(graphql.GetFieldContext(ctx).Field.Alias)
	} else {
		result, err = _m.Edges.PkgEqualPkgAOrErr()
	}
	if IsNotLoaded(err) {
		result, err = _m.QueryPkgEqualPkgA().All(ctx)
	}
	return result, err
}

func (_m *PackageVersion) PkgEqualPkgB(ctx context.Context) (result []*PkgEqual, err error) {
	if fc := graphql.GetFieldContext(ctx); fc != nil && fc.Field.Alias != "" {
		result, err = _m.NamedPkgEqualPkgB(graphql.GetFieldContext(ctx).Field.Alias)
	} else {
		result, err = _m.Edges.PkgEqualPkgBOrErr()
	}
	if IsNotLoaded(err) {
		result, err = _m.QueryPkgEqualPkgB().All(ctx)
	}
	return result, err
}

func (_m *PackageVersion) Poc(ctx context.Context) (result []*PointOfContact, err error) {
	if fc := graphql.GetFieldContext(ctx); fc != nil && fc.Field.Alias != "" {
		result, err = _m.NamedPoc(graphql.GetFieldContext(ctx).Field.Alias)
	} else {
		result, err = _m.Edges.PocOrErr()
	}
	if IsNotLoaded(err) {
		result, err = _m.QueryPoc().All(ctx)
	}
	return result, err
}

func (_m *PackageVersion) CertifyLegal(ctx context.Context) (result []*CertifyLegal, err error) {
	if fc := graphql.GetFieldContext(ctx); fc != nil && fc.Field.Alias != "" {
		result, err = _m.NamedCertifyLegal(graphql.GetFieldContext(ctx).Field.Alias)
	} else {
		result, err = _m.Edges.CertifyLegalOrErr()
	}
	if IsNotLoaded(err) {
		result, err = _m.QueryCertifyLegal().All(ctx)
	}
	return result, err
}

func (_m *PkgEqual) PackageA(ctx context.Context) (*PackageVersion, error) {
	result, err := _m.Edges.PackageAOrErr()
	if IsNotLoaded(err) {
		result, err = _m.QueryPackageA().Only(ctx)
	}
	return result, err
}

func (_m *PkgEqual) PackageB(ctx context.Context) (*PackageVersion, error) {
	result, err := _m.Edges.PackageBOrErr()
	if IsNotLoaded(err) {
		result, err = _m.QueryPackageB().Only(ctx)
	}
	return result, err
}

func (_m *PointOfContact) Source(ctx context.Context) (*SourceName, error) {
	result, err := _m.Edges.SourceOrErr()
	if IsNotLoaded(err) {
		result, err = _m.QuerySource().Only(ctx)
	}
	return result, MaskNotFound(err)
}

func (_m *PointOfContact) PackageVersion(ctx context.Context) (*PackageVersion, error) {
	result, err := _m.Edges.PackageVersionOrErr()
	if IsNotLoaded(err) {
		result, err = _m.QueryPackageVersion().Only(ctx)
	}
	return result, MaskNotFound(err)
}

func (_m *PointOfContact) AllVersions(ctx context.Context) (*PackageName, error) {
	result, err := _m.Edges.AllVersionsOrErr()
	if IsNotLoaded(err) {
		result, err = _m.QueryAllVersions().Only(ctx)
	}
	return result, MaskNotFound(err)
}

func (_m *PointOfContact) Artifact(ctx context.Context) (*Artifact, error) {
	result, err := _m.Edges.ArtifactOrErr()
	if IsNotLoaded(err) {
		result, err = _m.QueryArtifact().Only(ctx)
	}
	return result, MaskNotFound(err)
}

func (_m *SLSAAttestation) BuiltFrom(ctx context.Context) (result []*Artifact, err error) {
	if fc := graphql.GetFieldContext(ctx); fc != nil && fc.Field.Alias != "" {
		result, err = _m.NamedBuiltFrom(graphql.GetFieldContext(ctx).Field.Alias)
	} else {
		result, err = _m.Edges.BuiltFromOrErr()
	}
	if IsNotLoaded(err) {
		result, err = _m.QueryBuiltFrom().All(ctx)
	}
	return result, err
}

func (_m *SLSAAttestation) BuiltBy(ctx context.Context) (*Builder, error) {
	result, err := _m.Edges.BuiltByOrErr()
	if IsNotLoaded(err) {
		result, err = _m.QueryBuiltBy().Only(ctx)
	}
	return result, err
}

func (_m *SLSAAttestation) Subject(ctx context.Context) (*Artifact, error) {
	result, err := _m.Edges.SubjectOrErr()
	if IsNotLoaded(err) {
		result, err = _m.QuerySubject().Only(ctx)
	}
	return result, err
}

func (_m *SourceName) Occurrences(ctx context.Context) (result []*Occurrence, err error) {
	if fc := graphql.GetFieldContext(ctx); fc != nil && fc.Field.Alias != "" {
		result, err = _m.NamedOccurrences(graphql.GetFieldContext(ctx).Field.Alias)
	} else {
		result, err = _m.Edges.OccurrencesOrErr()
	}
	if IsNotLoaded(err) {
		result, err = _m.QueryOccurrences().All(ctx)
	}
	return result, err
}

func (_m *SourceName) HasSourceAt(ctx context.Context) (result []*HasSourceAt, err error) {
	if fc := graphql.GetFieldContext(ctx); fc != nil && fc.Field.Alias != "" {
		result, err = _m.NamedHasSourceAt(graphql.GetFieldContext(ctx).Field.Alias)
	} else {
		result, err = _m.Edges.HasSourceAtOrErr()
	}
	if IsNotLoaded(err) {
		result, err = _m.QueryHasSourceAt().All(ctx)
	}
	return result, err
}

func (_m *SourceName) Scorecard(ctx context.Context) (result []*CertifyScorecard, err error) {
	if fc := graphql.GetFieldContext(ctx); fc != nil && fc.Field.Alias != "" {
		result, err = _m.NamedScorecard(graphql.GetFieldContext(ctx).Field.Alias)
	} else {
		result, err = _m.Edges.ScorecardOrErr()
	}
	if IsNotLoaded(err) {
		result, err = _m.QueryScorecard().All(ctx)
	}
	return result, err
}

func (_m *SourceName) Certification(ctx context.Context) (result []*Certification, err error) {
	if fc := graphql.GetFieldContext(ctx); fc != nil && fc.Field.Alias != "" {
		result, err = _m.NamedCertification(graphql.GetFieldContext(ctx).Field.Alias)
	} else {
		result, err = _m.Edges.CertificationOrErr()
	}
	if IsNotLoaded(err) {
		result, err = _m.QueryCertification().All(ctx)
	}
	return result, err
}

func (_m *SourceName) Metadata(ctx context.Context) (result []*HasMetadata, err error) {
	if fc := graphql.GetFieldContext(ctx); fc != nil && fc.Field.Alias != "" {
		result, err = _m.NamedMetadata(graphql.GetFieldContext(ctx).Field.Alias)
	} else {
		result, err = _m.Edges.MetadataOrErr()
	}
	if IsNotLoaded(err) {
		result, err = _m.QueryMetadata().All(ctx)
	}
	return result, err
}

func (_m *SourceName) Poc(ctx context.Context) (result []*PointOfContact, err error) {
	if fc := graphql.GetFieldContext(ctx); fc != nil && fc.Field.Alias != "" {
		result, err = _m.NamedPoc(graphql.GetFieldContext(ctx).Field.Alias)
	} else {
		result, err = _m.Edges.PocOrErr()
	}
	if IsNotLoaded(err) {
		result, err = _m.QueryPoc().All(ctx)
	}
	return result, err
}

func (_m *SourceName) CertifyLegal(ctx context.Context) (result []*CertifyLegal, err error) {
	if fc := graphql.GetFieldContext(ctx); fc != nil && fc.Field.Alias != "" {
		result, err = _m.NamedCertifyLegal(graphql.GetFieldContext(ctx).Field.Alias)
	} else {
		result, err = _m.Edges.CertifyLegalOrErr()
	}
	if IsNotLoaded(err) {
		result, err = _m.QueryCertifyLegal().All(ctx)
	}
	return result, err
}

func (_m *VulnEqual) VulnerabilityA(ctx context.Context) (*VulnerabilityID, error) {
	result, err := _m.Edges.VulnerabilityAOrErr()
	if IsNotLoaded(err) {
		result, err = _m.QueryVulnerabilityA().Only(ctx)
	}
	return result, err
}

func (_m *VulnEqual) VulnerabilityB(ctx context.Context) (*VulnerabilityID, error) {
	result, err := _m.Edges.VulnerabilityBOrErr()
	if IsNotLoaded(err) {
		result, err = _m.QueryVulnerabilityB().Only(ctx)
	}
	return result, err
}

func (_m *VulnerabilityID) VulnEqualVulnA(ctx context.Context) (result []*VulnEqual, err error) {
	if fc := graphql.GetFieldContext(ctx); fc != nil && fc.Field.Alias != "" {
		result, err = _m.NamedVulnEqualVulnA(graphql.GetFieldContext(ctx).Field.Alias)
	} else {
		result, err = _m.Edges.VulnEqualVulnAOrErr()
	}
	if IsNotLoaded(err) {
		result, err = _m.QueryVulnEqualVulnA().All(ctx)
	}
	return result, err
}

func (_m *VulnerabilityID) VulnEqualVulnB(ctx context.Context) (result []*VulnEqual, err error) {
	if fc := graphql.GetFieldContext(ctx); fc != nil && fc.Field.Alias != "" {
		result, err = _m.NamedVulnEqualVulnB(graphql.GetFieldContext(ctx).Field.Alias)
	} else {
		result, err = _m.Edges.VulnEqualVulnBOrErr()
	}
	if IsNotLoaded(err) {
		result, err = _m.QueryVulnEqualVulnB().All(ctx)
	}
	return result, err
}

func (_m *VulnerabilityID) Metadata(ctx context.Context) (result []*VulnerabilityMetadata, err error) {
	if fc := graphql.GetFieldContext(ctx); fc != nil && fc.Field.Alias != "" {
		result, err = _m.NamedMetadata(graphql.GetFieldContext(ctx).Field.Alias)
	} else {
		result, err = _m.Edges.MetadataOrErr()
	}
	if IsNotLoaded(err) {
		result, err = _m.QueryMetadata().All(ctx)
	}
	return result, err
}

func (_m *VulnerabilityID) CertifyVuln(ctx context.Context) (result []*CertifyVuln, err error) {
	if fc := graphql.GetFieldContext(ctx); fc != nil && fc.Field.Alias != "" {
		result, err = _m.NamedCertifyVuln(graphql.GetFieldContext(ctx).Field.Alias)
	} else {
		result, err = _m.Edges.CertifyVulnOrErr()
	}
	if IsNotLoaded(err) {
		result, err = _m.QueryCertifyVuln().All(ctx)
	}
	return result, err
}

func (_m *VulnerabilityID) Vex(ctx context.Context) (result []*CertifyVex, err error) {
	if fc := graphql.GetFieldContext(ctx); fc != nil && fc.Field.Alias != "" {
		result, err = _m.NamedVex(graphql.GetFieldContext(ctx).Field.Alias)
	} else {
		result, err = _m.Edges.VexOrErr()
	}
	if IsNotLoaded(err) {
		result, err = _m.QueryVex().All(ctx)
	}
	return result, err
}

func (_m *VulnerabilityMetadata) VulnerabilityID(ctx context.Context) (*VulnerabilityID, error) {
	result, err := _m.Edges.VulnerabilityIDOrErr()
	if IsNotLoaded(err) {
		result, err = _m.QueryVulnerabilityID().Only(ctx)
	}
	return result, err
}
