// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/guacsec/guac/pkg/assembler/backends/ent/isoccurrence"
	"github.com/guacsec/guac/pkg/assembler/backends/ent/predicate"
)

// IsOccurrenceDelete is the builder for deleting a IsOccurrence entity.
type IsOccurrenceDelete struct {
	config
	hooks    []Hook
	mutation *IsOccurrenceMutation
}

// Where appends a list predicates to the IsOccurrenceDelete builder.
func (iod *IsOccurrenceDelete) Where(ps ...predicate.IsOccurrence) *IsOccurrenceDelete {
	iod.mutation.Where(ps...)
	return iod
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (iod *IsOccurrenceDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, iod.sqlExec, iod.mutation, iod.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (iod *IsOccurrenceDelete) ExecX(ctx context.Context) int {
	n, err := iod.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (iod *IsOccurrenceDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(isoccurrence.Table, sqlgraph.NewFieldSpec(isoccurrence.FieldID, field.TypeInt))
	if ps := iod.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, iod.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	iod.mutation.done = true
	return affected, err
}

// IsOccurrenceDeleteOne is the builder for deleting a single IsOccurrence entity.
type IsOccurrenceDeleteOne struct {
	iod *IsOccurrenceDelete
}

// Where appends a list predicates to the IsOccurrenceDelete builder.
func (iodo *IsOccurrenceDeleteOne) Where(ps ...predicate.IsOccurrence) *IsOccurrenceDeleteOne {
	iodo.iod.mutation.Where(ps...)
	return iodo
}

// Exec executes the deletion query.
func (iodo *IsOccurrenceDeleteOne) Exec(ctx context.Context) error {
	n, err := iodo.iod.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{isoccurrence.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (iodo *IsOccurrenceDeleteOne) ExecX(ctx context.Context) {
	if err := iodo.Exec(ctx); err != nil {
		panic(err)
	}
}
