// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/guacsec/guac/pkg/assembler/backends/ent/artifact"
	"github.com/guacsec/guac/pkg/assembler/backends/ent/billofmaterials"
	"github.com/guacsec/guac/pkg/assembler/backends/ent/occurrence"
	"github.com/guacsec/guac/pkg/assembler/backends/ent/packageversion"
	"github.com/guacsec/guac/pkg/assembler/backends/ent/predicate"
	"github.com/guacsec/guac/pkg/assembler/backends/ent/sourcename"
)

// OccurrenceUpdate is the builder for updating Occurrence entities.
type OccurrenceUpdate struct {
	config
	hooks    []Hook
	mutation *OccurrenceMutation
}

// Where appends a list predicates to the OccurrenceUpdate builder.
func (_u *OccurrenceUpdate) Where(ps ...predicate.Occurrence) *OccurrenceUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetArtifactID sets the "artifact_id" field.
func (_u *OccurrenceUpdate) SetArtifactID(v uuid.UUID) *OccurrenceUpdate {
	_u.mutation.SetArtifactID(v)
	return _u
}

// SetNillableArtifactID sets the "artifact_id" field if the given value is not nil.
func (_u *OccurrenceUpdate) SetNillableArtifactID(v *uuid.UUID) *OccurrenceUpdate {
	if v != nil {
		_u.SetArtifactID(*v)
	}
	return _u
}

// SetJustification sets the "justification" field.
func (_u *OccurrenceUpdate) SetJustification(v string) *OccurrenceUpdate {
	_u.mutation.SetJustification(v)
	return _u
}

// SetNillableJustification sets the "justification" field if the given value is not nil.
func (_u *OccurrenceUpdate) SetNillableJustification(v *string) *OccurrenceUpdate {
	if v != nil {
		_u.SetJustification(*v)
	}
	return _u
}

// SetOrigin sets the "origin" field.
func (_u *OccurrenceUpdate) SetOrigin(v string) *OccurrenceUpdate {
	_u.mutation.SetOrigin(v)
	return _u
}

// SetNillableOrigin sets the "origin" field if the given value is not nil.
func (_u *OccurrenceUpdate) SetNillableOrigin(v *string) *OccurrenceUpdate {
	if v != nil {
		_u.SetOrigin(*v)
	}
	return _u
}

// SetCollector sets the "collector" field.
func (_u *OccurrenceUpdate) SetCollector(v string) *OccurrenceUpdate {
	_u.mutation.SetCollector(v)
	return _u
}

// SetNillableCollector sets the "collector" field if the given value is not nil.
func (_u *OccurrenceUpdate) SetNillableCollector(v *string) *OccurrenceUpdate {
	if v != nil {
		_u.SetCollector(*v)
	}
	return _u
}

// SetDocumentRef sets the "document_ref" field.
func (_u *OccurrenceUpdate) SetDocumentRef(v string) *OccurrenceUpdate {
	_u.mutation.SetDocumentRef(v)
	return _u
}

// SetNillableDocumentRef sets the "document_ref" field if the given value is not nil.
func (_u *OccurrenceUpdate) SetNillableDocumentRef(v *string) *OccurrenceUpdate {
	if v != nil {
		_u.SetDocumentRef(*v)
	}
	return _u
}

// SetSourceID sets the "source_id" field.
func (_u *OccurrenceUpdate) SetSourceID(v uuid.UUID) *OccurrenceUpdate {
	_u.mutation.SetSourceID(v)
	return _u
}

// SetNillableSourceID sets the "source_id" field if the given value is not nil.
func (_u *OccurrenceUpdate) SetNillableSourceID(v *uuid.UUID) *OccurrenceUpdate {
	if v != nil {
		_u.SetSourceID(*v)
	}
	return _u
}

// ClearSourceID clears the value of the "source_id" field.
func (_u *OccurrenceUpdate) ClearSourceID() *OccurrenceUpdate {
	_u.mutation.ClearSourceID()
	return _u
}

// SetPackageID sets the "package_id" field.
func (_u *OccurrenceUpdate) SetPackageID(v uuid.UUID) *OccurrenceUpdate {
	_u.mutation.SetPackageID(v)
	return _u
}

// SetNillablePackageID sets the "package_id" field if the given value is not nil.
func (_u *OccurrenceUpdate) SetNillablePackageID(v *uuid.UUID) *OccurrenceUpdate {
	if v != nil {
		_u.SetPackageID(*v)
	}
	return _u
}

// ClearPackageID clears the value of the "package_id" field.
func (_u *OccurrenceUpdate) ClearPackageID() *OccurrenceUpdate {
	_u.mutation.ClearPackageID()
	return _u
}

// SetArtifact sets the "artifact" edge to the Artifact entity.
func (_u *OccurrenceUpdate) SetArtifact(v *Artifact) *OccurrenceUpdate {
	return _u.SetArtifactID(v.ID)
}

// SetPackage sets the "package" edge to the PackageVersion entity.
func (_u *OccurrenceUpdate) SetPackage(v *PackageVersion) *OccurrenceUpdate {
	return _u.SetPackageID(v.ID)
}

// SetSource sets the "source" edge to the SourceName entity.
func (_u *OccurrenceUpdate) SetSource(v *SourceName) *OccurrenceUpdate {
	return _u.SetSourceID(v.ID)
}

// AddIncludedInSbomIDs adds the "included_in_sboms" edge to the BillOfMaterials entity by IDs.
func (_u *OccurrenceUpdate) AddIncludedInSbomIDs(ids ...uuid.UUID) *OccurrenceUpdate {
	_u.mutation.AddIncludedInSbomIDs(ids...)
	return _u
}

// AddIncludedInSboms adds the "included_in_sboms" edges to the BillOfMaterials entity.
func (_u *OccurrenceUpdate) AddIncludedInSboms(v ...*BillOfMaterials) *OccurrenceUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddIncludedInSbomIDs(ids...)
}

// Mutation returns the OccurrenceMutation object of the builder.
func (_u *OccurrenceUpdate) Mutation() *OccurrenceMutation {
	return _u.mutation
}

// ClearArtifact clears the "artifact" edge to the Artifact entity.
func (_u *OccurrenceUpdate) ClearArtifact() *OccurrenceUpdate {
	_u.mutation.ClearArtifact()
	return _u
}

// ClearPackage clears the "package" edge to the PackageVersion entity.
func (_u *OccurrenceUpdate) ClearPackage() *OccurrenceUpdate {
	_u.mutation.ClearPackage()
	return _u
}

// ClearSource clears the "source" edge to the SourceName entity.
func (_u *OccurrenceUpdate) ClearSource() *OccurrenceUpdate {
	_u.mutation.ClearSource()
	return _u
}

// ClearIncludedInSboms clears all "included_in_sboms" edges to the BillOfMaterials entity.
func (_u *OccurrenceUpdate) ClearIncludedInSboms() *OccurrenceUpdate {
	_u.mutation.ClearIncludedInSboms()
	return _u
}

// RemoveIncludedInSbomIDs removes the "included_in_sboms" edge to BillOfMaterials entities by IDs.
func (_u *OccurrenceUpdate) RemoveIncludedInSbomIDs(ids ...uuid.UUID) *OccurrenceUpdate {
	_u.mutation.RemoveIncludedInSbomIDs(ids...)
	return _u
}

// RemoveIncludedInSboms removes "included_in_sboms" edges to BillOfMaterials entities.
func (_u *OccurrenceUpdate) RemoveIncludedInSboms(v ...*BillOfMaterials) *OccurrenceUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveIncludedInSbomIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *OccurrenceUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *OccurrenceUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *OccurrenceUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *OccurrenceUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *OccurrenceUpdate) check() error {
	if _u.mutation.ArtifactCleared() && len(_u.mutation.ArtifactIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Occurrence.artifact"`)
	}
	return nil
}

func (_u *OccurrenceUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(occurrence.Table, occurrence.Columns, sqlgraph.NewFieldSpec(occurrence.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Justification(); ok {
		_spec.SetField(occurrence.FieldJustification, field.TypeString, value)
	}
	if value, ok := _u.mutation.Origin(); ok {
		_spec.SetField(occurrence.FieldOrigin, field.TypeString, value)
	}
	if value, ok := _u.mutation.Collector(); ok {
		_spec.SetField(occurrence.FieldCollector, field.TypeString, value)
	}
	if value, ok := _u.mutation.DocumentRef(); ok {
		_spec.SetField(occurrence.FieldDocumentRef, field.TypeString, value)
	}
	if _u.mutation.ArtifactCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   occurrence.ArtifactTable,
			Columns: []string{occurrence.ArtifactColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(artifact.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ArtifactIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   occurrence.ArtifactTable,
			Columns: []string{occurrence.ArtifactColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(artifact.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.PackageCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   occurrence.PackageTable,
			Columns: []string{occurrence.PackageColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(packageversion.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PackageIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   occurrence.PackageTable,
			Columns: []string{occurrence.PackageColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(packageversion.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.SourceCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   occurrence.SourceTable,
			Columns: []string{occurrence.SourceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sourcename.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SourceIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   occurrence.SourceTable,
			Columns: []string{occurrence.SourceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sourcename.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.IncludedInSbomsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   occurrence.IncludedInSbomsTable,
			Columns: occurrence.IncludedInSbomsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(billofmaterials.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedIncludedInSbomsIDs(); len(nodes) > 0 && !_u.mutation.IncludedInSbomsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   occurrence.IncludedInSbomsTable,
			Columns: occurrence.IncludedInSbomsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(billofmaterials.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.IncludedInSbomsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   occurrence.IncludedInSbomsTable,
			Columns: occurrence.IncludedInSbomsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(billofmaterials.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{occurrence.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// OccurrenceUpdateOne is the builder for updating a single Occurrence entity.
type OccurrenceUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *OccurrenceMutation
}

// SetArtifactID sets the "artifact_id" field.
func (_u *OccurrenceUpdateOne) SetArtifactID(v uuid.UUID) *OccurrenceUpdateOne {
	_u.mutation.SetArtifactID(v)
	return _u
}

// SetNillableArtifactID sets the "artifact_id" field if the given value is not nil.
func (_u *OccurrenceUpdateOne) SetNillableArtifactID(v *uuid.UUID) *OccurrenceUpdateOne {
	if v != nil {
		_u.SetArtifactID(*v)
	}
	return _u
}

// SetJustification sets the "justification" field.
func (_u *OccurrenceUpdateOne) SetJustification(v string) *OccurrenceUpdateOne {
	_u.mutation.SetJustification(v)
	return _u
}

// SetNillableJustification sets the "justification" field if the given value is not nil.
func (_u *OccurrenceUpdateOne) SetNillableJustification(v *string) *OccurrenceUpdateOne {
	if v != nil {
		_u.SetJustification(*v)
	}
	return _u
}

// SetOrigin sets the "origin" field.
func (_u *OccurrenceUpdateOne) SetOrigin(v string) *OccurrenceUpdateOne {
	_u.mutation.SetOrigin(v)
	return _u
}

// SetNillableOrigin sets the "origin" field if the given value is not nil.
func (_u *OccurrenceUpdateOne) SetNillableOrigin(v *string) *OccurrenceUpdateOne {
	if v != nil {
		_u.SetOrigin(*v)
	}
	return _u
}

// SetCollector sets the "collector" field.
func (_u *OccurrenceUpdateOne) SetCollector(v string) *OccurrenceUpdateOne {
	_u.mutation.SetCollector(v)
	return _u
}

// SetNillableCollector sets the "collector" field if the given value is not nil.
func (_u *OccurrenceUpdateOne) SetNillableCollector(v *string) *OccurrenceUpdateOne {
	if v != nil {
		_u.SetCollector(*v)
	}
	return _u
}

// SetDocumentRef sets the "document_ref" field.
func (_u *OccurrenceUpdateOne) SetDocumentRef(v string) *OccurrenceUpdateOne {
	_u.mutation.SetDocumentRef(v)
	return _u
}

// SetNillableDocumentRef sets the "document_ref" field if the given value is not nil.
func (_u *OccurrenceUpdateOne) SetNillableDocumentRef(v *string) *OccurrenceUpdateOne {
	if v != nil {
		_u.SetDocumentRef(*v)
	}
	return _u
}

// SetSourceID sets the "source_id" field.
func (_u *OccurrenceUpdateOne) SetSourceID(v uuid.UUID) *OccurrenceUpdateOne {
	_u.mutation.SetSourceID(v)
	return _u
}

// SetNillableSourceID sets the "source_id" field if the given value is not nil.
func (_u *OccurrenceUpdateOne) SetNillableSourceID(v *uuid.UUID) *OccurrenceUpdateOne {
	if v != nil {
		_u.SetSourceID(*v)
	}
	return _u
}

// ClearSourceID clears the value of the "source_id" field.
func (_u *OccurrenceUpdateOne) ClearSourceID() *OccurrenceUpdateOne {
	_u.mutation.ClearSourceID()
	return _u
}

// SetPackageID sets the "package_id" field.
func (_u *OccurrenceUpdateOne) SetPackageID(v uuid.UUID) *OccurrenceUpdateOne {
	_u.mutation.SetPackageID(v)
	return _u
}

// SetNillablePackageID sets the "package_id" field if the given value is not nil.
func (_u *OccurrenceUpdateOne) SetNillablePackageID(v *uuid.UUID) *OccurrenceUpdateOne {
	if v != nil {
		_u.SetPackageID(*v)
	}
	return _u
}

// ClearPackageID clears the value of the "package_id" field.
func (_u *OccurrenceUpdateOne) ClearPackageID() *OccurrenceUpdateOne {
	_u.mutation.ClearPackageID()
	return _u
}

// SetArtifact sets the "artifact" edge to the Artifact entity.
func (_u *OccurrenceUpdateOne) SetArtifact(v *Artifact) *OccurrenceUpdateOne {
	return _u.SetArtifactID(v.ID)
}

// SetPackage sets the "package" edge to the PackageVersion entity.
func (_u *OccurrenceUpdateOne) SetPackage(v *PackageVersion) *OccurrenceUpdateOne {
	return _u.SetPackageID(v.ID)
}

// SetSource sets the "source" edge to the SourceName entity.
func (_u *OccurrenceUpdateOne) SetSource(v *SourceName) *OccurrenceUpdateOne {
	return _u.SetSourceID(v.ID)
}

// AddIncludedInSbomIDs adds the "included_in_sboms" edge to the BillOfMaterials entity by IDs.
func (_u *OccurrenceUpdateOne) AddIncludedInSbomIDs(ids ...uuid.UUID) *OccurrenceUpdateOne {
	_u.mutation.AddIncludedInSbomIDs(ids...)
	return _u
}

// AddIncludedInSboms adds the "included_in_sboms" edges to the BillOfMaterials entity.
func (_u *OccurrenceUpdateOne) AddIncludedInSboms(v ...*BillOfMaterials) *OccurrenceUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddIncludedInSbomIDs(ids...)
}

// Mutation returns the OccurrenceMutation object of the builder.
func (_u *OccurrenceUpdateOne) Mutation() *OccurrenceMutation {
	return _u.mutation
}

// ClearArtifact clears the "artifact" edge to the Artifact entity.
func (_u *OccurrenceUpdateOne) ClearArtifact() *OccurrenceUpdateOne {
	_u.mutation.ClearArtifact()
	return _u
}

// ClearPackage clears the "package" edge to the PackageVersion entity.
func (_u *OccurrenceUpdateOne) ClearPackage() *OccurrenceUpdateOne {
	_u.mutation.ClearPackage()
	return _u
}

// ClearSource clears the "source" edge to the SourceName entity.
func (_u *OccurrenceUpdateOne) ClearSource() *OccurrenceUpdateOne {
	_u.mutation.ClearSource()
	return _u
}

// ClearIncludedInSboms clears all "included_in_sboms" edges to the BillOfMaterials entity.
func (_u *OccurrenceUpdateOne) ClearIncludedInSboms() *OccurrenceUpdateOne {
	_u.mutation.ClearIncludedInSboms()
	return _u
}

// RemoveIncludedInSbomIDs removes the "included_in_sboms" edge to BillOfMaterials entities by IDs.
func (_u *OccurrenceUpdateOne) RemoveIncludedInSbomIDs(ids ...uuid.UUID) *OccurrenceUpdateOne {
	_u.mutation.RemoveIncludedInSbomIDs(ids...)
	return _u
}

// RemoveIncludedInSboms removes "included_in_sboms" edges to BillOfMaterials entities.
func (_u *OccurrenceUpdateOne) RemoveIncludedInSboms(v ...*BillOfMaterials) *OccurrenceUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveIncludedInSbomIDs(ids...)
}

// Where appends a list predicates to the OccurrenceUpdate builder.
func (_u *OccurrenceUpdateOne) Where(ps ...predicate.Occurrence) *OccurrenceUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *OccurrenceUpdateOne) Select(field string, fields ...string) *OccurrenceUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Occurrence entity.
func (_u *OccurrenceUpdateOne) Save(ctx context.Context) (*Occurrence, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *OccurrenceUpdateOne) SaveX(ctx context.Context) *Occurrence {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *OccurrenceUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *OccurrenceUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *OccurrenceUpdateOne) check() error {
	if _u.mutation.ArtifactCleared() && len(_u.mutation.ArtifactIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Occurrence.artifact"`)
	}
	return nil
}

func (_u *OccurrenceUpdateOne) sqlSave(ctx context.Context) (_node *Occurrence, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(occurrence.Table, occurrence.Columns, sqlgraph.NewFieldSpec(occurrence.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Occurrence.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, occurrence.FieldID)
		for _, f := range fields {
			if !occurrence.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != occurrence.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Justification(); ok {
		_spec.SetField(occurrence.FieldJustification, field.TypeString, value)
	}
	if value, ok := _u.mutation.Origin(); ok {
		_spec.SetField(occurrence.FieldOrigin, field.TypeString, value)
	}
	if value, ok := _u.mutation.Collector(); ok {
		_spec.SetField(occurrence.FieldCollector, field.TypeString, value)
	}
	if value, ok := _u.mutation.DocumentRef(); ok {
		_spec.SetField(occurrence.FieldDocumentRef, field.TypeString, value)
	}
	if _u.mutation.ArtifactCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   occurrence.ArtifactTable,
			Columns: []string{occurrence.ArtifactColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(artifact.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ArtifactIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   occurrence.ArtifactTable,
			Columns: []string{occurrence.ArtifactColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(artifact.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.PackageCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   occurrence.PackageTable,
			Columns: []string{occurrence.PackageColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(packageversion.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PackageIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   occurrence.PackageTable,
			Columns: []string{occurrence.PackageColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(packageversion.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.SourceCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   occurrence.SourceTable,
			Columns: []string{occurrence.SourceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sourcename.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SourceIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   occurrence.SourceTable,
			Columns: []string{occurrence.SourceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sourcename.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.IncludedInSbomsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   occurrence.IncludedInSbomsTable,
			Columns: occurrence.IncludedInSbomsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(billofmaterials.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedIncludedInSbomsIDs(); len(nodes) > 0 && !_u.mutation.IncludedInSbomsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   occurrence.IncludedInSbomsTable,
			Columns: occurrence.IncludedInSbomsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(billofmaterials.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.IncludedInSbomsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   occurrence.IncludedInSbomsTable,
			Columns: occurrence.IncludedInSbomsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(billofmaterials.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Occurrence{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{occurrence.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
