// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/guacsec/guac/pkg/assembler/backends/ent/artifact"
	"github.com/guacsec/guac/pkg/assembler/backends/ent/occurrence"
	"github.com/guacsec/guac/pkg/assembler/backends/ent/packageversion"
	"github.com/guacsec/guac/pkg/assembler/backends/ent/sourcename"
)

// Occurrence is the model entity for the Occurrence schema.
type Occurrence struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// PackageID holds the value of the "package_id" field.
	PackageID *int `json:"package_id,omitempty"`
	// SourceID holds the value of the "source_id" field.
	SourceID *int `json:"source_id,omitempty"`
	// The artifact in the relationship
	ArtifactID int `json:"artifact_id,omitempty"`
	// Justification for the attested relationship
	Justification string `json:"justification,omitempty"`
	// Document from which this attestation is generated from
	Origin string `json:"origin,omitempty"`
	// GUAC collector for the document
	Collector string `json:"collector,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the OccurrenceQuery when eager-loading is set.
	Edges        OccurrenceEdges `json:"edges"`
	selectValues sql.SelectValues
}

// OccurrenceEdges holds the relations/edges for other nodes in the graph.
type OccurrenceEdges struct {
	// PackageVersion holds the value of the package_version edge.
	PackageVersion *PackageVersion `json:"package_version,omitempty"`
	// Source holds the value of the source edge.
	Source *SourceName `json:"source,omitempty"`
	// Artifact holds the value of the artifact edge.
	Artifact *Artifact `json:"artifact,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [3]bool
}

// PackageVersionOrErr returns the PackageVersion value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e OccurrenceEdges) PackageVersionOrErr() (*PackageVersion, error) {
	if e.loadedTypes[0] {
		if e.PackageVersion == nil {
			// Edge was loaded but was not found.
			return nil, &NotFoundError{label: packageversion.Label}
		}
		return e.PackageVersion, nil
	}
	return nil, &NotLoadedError{edge: "package_version"}
}

// SourceOrErr returns the Source value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e OccurrenceEdges) SourceOrErr() (*SourceName, error) {
	if e.loadedTypes[1] {
		if e.Source == nil {
			// Edge was loaded but was not found.
			return nil, &NotFoundError{label: sourcename.Label}
		}
		return e.Source, nil
	}
	return nil, &NotLoadedError{edge: "source"}
}

// ArtifactOrErr returns the Artifact value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e OccurrenceEdges) ArtifactOrErr() (*Artifact, error) {
	if e.loadedTypes[2] {
		if e.Artifact == nil {
			// Edge was loaded but was not found.
			return nil, &NotFoundError{label: artifact.Label}
		}
		return e.Artifact, nil
	}
	return nil, &NotLoadedError{edge: "artifact"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Occurrence) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case occurrence.FieldID, occurrence.FieldPackageID, occurrence.FieldSourceID, occurrence.FieldArtifactID:
			values[i] = new(sql.NullInt64)
		case occurrence.FieldJustification, occurrence.FieldOrigin, occurrence.FieldCollector:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Occurrence fields.
func (o *Occurrence) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case occurrence.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			o.ID = int(value.Int64)
		case occurrence.FieldPackageID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field package_id", values[i])
			} else if value.Valid {
				o.PackageID = new(int)
				*o.PackageID = int(value.Int64)
			}
		case occurrence.FieldSourceID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field source_id", values[i])
			} else if value.Valid {
				o.SourceID = new(int)
				*o.SourceID = int(value.Int64)
			}
		case occurrence.FieldArtifactID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field artifact_id", values[i])
			} else if value.Valid {
				o.ArtifactID = int(value.Int64)
			}
		case occurrence.FieldJustification:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field justification", values[i])
			} else if value.Valid {
				o.Justification = value.String
			}
		case occurrence.FieldOrigin:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field origin", values[i])
			} else if value.Valid {
				o.Origin = value.String
			}
		case occurrence.FieldCollector:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field collector", values[i])
			} else if value.Valid {
				o.Collector = value.String
			}
		default:
			o.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Occurrence.
// This includes values selected through modifiers, order, etc.
func (o *Occurrence) Value(name string) (ent.Value, error) {
	return o.selectValues.Get(name)
}

// QueryPackageVersion queries the "package_version" edge of the Occurrence entity.
func (o *Occurrence) QueryPackageVersion() *PackageVersionQuery {
	return NewOccurrenceClient(o.config).QueryPackageVersion(o)
}

// QuerySource queries the "source" edge of the Occurrence entity.
func (o *Occurrence) QuerySource() *SourceNameQuery {
	return NewOccurrenceClient(o.config).QuerySource(o)
}

// QueryArtifact queries the "artifact" edge of the Occurrence entity.
func (o *Occurrence) QueryArtifact() *ArtifactQuery {
	return NewOccurrenceClient(o.config).QueryArtifact(o)
}

// Update returns a builder for updating this Occurrence.
// Note that you need to call Occurrence.Unwrap() before calling this method if this Occurrence
// was returned from a transaction, and the transaction was committed or rolled back.
func (o *Occurrence) Update() *OccurrenceUpdateOne {
	return NewOccurrenceClient(o.config).UpdateOne(o)
}

// Unwrap unwraps the Occurrence entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (o *Occurrence) Unwrap() *Occurrence {
	_tx, ok := o.config.driver.(*txDriver)
	if !ok {
		panic("ent: Occurrence is not a transactional entity")
	}
	o.config.driver = _tx.drv
	return o
}

// String implements the fmt.Stringer.
func (o *Occurrence) String() string {
	var builder strings.Builder
	builder.WriteString("Occurrence(")
	builder.WriteString(fmt.Sprintf("id=%v, ", o.ID))
	if v := o.PackageID; v != nil {
		builder.WriteString("package_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := o.SourceID; v != nil {
		builder.WriteString("source_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("artifact_id=")
	builder.WriteString(fmt.Sprintf("%v", o.ArtifactID))
	builder.WriteString(", ")
	builder.WriteString("justification=")
	builder.WriteString(o.Justification)
	builder.WriteString(", ")
	builder.WriteString("origin=")
	builder.WriteString(o.Origin)
	builder.WriteString(", ")
	builder.WriteString("collector=")
	builder.WriteString(o.Collector)
	builder.WriteByte(')')
	return builder.String()
}

// Occurrences is a parsable slice of Occurrence.
type Occurrences []*Occurrence
