// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/guacsec/guac/pkg/assembler/backends/ent/packagename"
	"github.com/guacsec/guac/pkg/assembler/backends/ent/packagenamespace"
	"github.com/guacsec/guac/pkg/assembler/backends/ent/packagenode"
)

// PackageNamespaceCreate is the builder for creating a PackageNamespace entity.
type PackageNamespaceCreate struct {
	config
	mutation *PackageNamespaceMutation
	hooks    []Hook
}

// SetPackageID sets the "package_id" field.
func (pnc *PackageNamespaceCreate) SetPackageID(i int) *PackageNamespaceCreate {
	pnc.mutation.SetPackageID(i)
	return pnc
}

// SetNamespace sets the "namespace" field.
func (pnc *PackageNamespaceCreate) SetNamespace(s string) *PackageNamespaceCreate {
	pnc.mutation.SetNamespace(s)
	return pnc
}

// SetPackage sets the "package" edge to the PackageNode entity.
func (pnc *PackageNamespaceCreate) SetPackage(p *PackageNode) *PackageNamespaceCreate {
	return pnc.SetPackageID(p.ID)
}

// AddNameIDs adds the "names" edge to the PackageName entity by IDs.
func (pnc *PackageNamespaceCreate) AddNameIDs(ids ...int) *PackageNamespaceCreate {
	pnc.mutation.AddNameIDs(ids...)
	return pnc
}

// AddNames adds the "names" edges to the PackageName entity.
func (pnc *PackageNamespaceCreate) AddNames(p ...*PackageName) *PackageNamespaceCreate {
	ids := make([]int, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return pnc.AddNameIDs(ids...)
}

// Mutation returns the PackageNamespaceMutation object of the builder.
func (pnc *PackageNamespaceCreate) Mutation() *PackageNamespaceMutation {
	return pnc.mutation
}

// Save creates the PackageNamespace in the database.
func (pnc *PackageNamespaceCreate) Save(ctx context.Context) (*PackageNamespace, error) {
	return withHooks(ctx, pnc.sqlSave, pnc.mutation, pnc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (pnc *PackageNamespaceCreate) SaveX(ctx context.Context) *PackageNamespace {
	v, err := pnc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (pnc *PackageNamespaceCreate) Exec(ctx context.Context) error {
	_, err := pnc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pnc *PackageNamespaceCreate) ExecX(ctx context.Context) {
	if err := pnc.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (pnc *PackageNamespaceCreate) check() error {
	if _, ok := pnc.mutation.PackageID(); !ok {
		return &ValidationError{Name: "package_id", err: errors.New(`ent: missing required field "PackageNamespace.package_id"`)}
	}
	if _, ok := pnc.mutation.Namespace(); !ok {
		return &ValidationError{Name: "namespace", err: errors.New(`ent: missing required field "PackageNamespace.namespace"`)}
	}
	if v, ok := pnc.mutation.Namespace(); ok {
		if err := packagenamespace.NamespaceValidator(v); err != nil {
			return &ValidationError{Name: "namespace", err: fmt.Errorf(`ent: validator failed for field "PackageNamespace.namespace": %w`, err)}
		}
	}
	if _, ok := pnc.mutation.PackageID(); !ok {
		return &ValidationError{Name: "package", err: errors.New(`ent: missing required edge "PackageNamespace.package"`)}
	}
	return nil
}

func (pnc *PackageNamespaceCreate) sqlSave(ctx context.Context) (*PackageNamespace, error) {
	if err := pnc.check(); err != nil {
		return nil, err
	}
	_node, _spec := pnc.createSpec()
	if err := sqlgraph.CreateNode(ctx, pnc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	pnc.mutation.id = &_node.ID
	pnc.mutation.done = true
	return _node, nil
}

func (pnc *PackageNamespaceCreate) createSpec() (*PackageNamespace, *sqlgraph.CreateSpec) {
	var (
		_node = &PackageNamespace{config: pnc.config}
		_spec = sqlgraph.NewCreateSpec(packagenamespace.Table, sqlgraph.NewFieldSpec(packagenamespace.FieldID, field.TypeInt))
	)
	if value, ok := pnc.mutation.Namespace(); ok {
		_spec.SetField(packagenamespace.FieldNamespace, field.TypeString, value)
		_node.Namespace = value
	}
	if nodes := pnc.mutation.PackageIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   packagenamespace.PackageTable,
			Columns: []string{packagenamespace.PackageColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(packagenode.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.PackageID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := pnc.mutation.NamesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   packagenamespace.NamesTable,
			Columns: []string{packagenamespace.NamesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(packagename.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// PackageNamespaceCreateBulk is the builder for creating many PackageNamespace entities in bulk.
type PackageNamespaceCreateBulk struct {
	config
	builders []*PackageNamespaceCreate
}

// Save creates the PackageNamespace entities in the database.
func (pncb *PackageNamespaceCreateBulk) Save(ctx context.Context) ([]*PackageNamespace, error) {
	specs := make([]*sqlgraph.CreateSpec, len(pncb.builders))
	nodes := make([]*PackageNamespace, len(pncb.builders))
	mutators := make([]Mutator, len(pncb.builders))
	for i := range pncb.builders {
		func(i int, root context.Context) {
			builder := pncb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PackageNamespaceMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, pncb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, pncb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, pncb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (pncb *PackageNamespaceCreateBulk) SaveX(ctx context.Context) []*PackageNamespace {
	v, err := pncb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (pncb *PackageNamespaceCreateBulk) Exec(ctx context.Context) error {
	_, err := pncb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pncb *PackageNamespaceCreateBulk) ExecX(ctx context.Context) {
	if err := pncb.Exec(ctx); err != nil {
		panic(err)
	}
}
