// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/guacsec/guac/pkg/assembler/backends/ent/packagenamespace"
	"github.com/guacsec/guac/pkg/assembler/backends/ent/packagenode"
)

// PackageNodeCreate is the builder for creating a PackageNode entity.
type PackageNodeCreate struct {
	config
	mutation *PackageNodeMutation
	hooks    []Hook
}

// SetType sets the "type" field.
func (pnc *PackageNodeCreate) SetType(s string) *PackageNodeCreate {
	pnc.mutation.SetType(s)
	return pnc
}

// AddNamespaceIDs adds the "namespaces" edge to the PackageNamespace entity by IDs.
func (pnc *PackageNodeCreate) AddNamespaceIDs(ids ...int) *PackageNodeCreate {
	pnc.mutation.AddNamespaceIDs(ids...)
	return pnc
}

// AddNamespaces adds the "namespaces" edges to the PackageNamespace entity.
func (pnc *PackageNodeCreate) AddNamespaces(p ...*PackageNamespace) *PackageNodeCreate {
	ids := make([]int, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return pnc.AddNamespaceIDs(ids...)
}

// Mutation returns the PackageNodeMutation object of the builder.
func (pnc *PackageNodeCreate) Mutation() *PackageNodeMutation {
	return pnc.mutation
}

// Save creates the PackageNode in the database.
func (pnc *PackageNodeCreate) Save(ctx context.Context) (*PackageNode, error) {
	return withHooks(ctx, pnc.sqlSave, pnc.mutation, pnc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (pnc *PackageNodeCreate) SaveX(ctx context.Context) *PackageNode {
	v, err := pnc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (pnc *PackageNodeCreate) Exec(ctx context.Context) error {
	_, err := pnc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pnc *PackageNodeCreate) ExecX(ctx context.Context) {
	if err := pnc.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (pnc *PackageNodeCreate) check() error {
	if _, ok := pnc.mutation.GetType(); !ok {
		return &ValidationError{Name: "type", err: errors.New(`ent: missing required field "PackageNode.type"`)}
	}
	if v, ok := pnc.mutation.GetType(); ok {
		if err := packagenode.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "PackageNode.type": %w`, err)}
		}
	}
	return nil
}

func (pnc *PackageNodeCreate) sqlSave(ctx context.Context) (*PackageNode, error) {
	if err := pnc.check(); err != nil {
		return nil, err
	}
	_node, _spec := pnc.createSpec()
	if err := sqlgraph.CreateNode(ctx, pnc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	pnc.mutation.id = &_node.ID
	pnc.mutation.done = true
	return _node, nil
}

func (pnc *PackageNodeCreate) createSpec() (*PackageNode, *sqlgraph.CreateSpec) {
	var (
		_node = &PackageNode{config: pnc.config}
		_spec = sqlgraph.NewCreateSpec(packagenode.Table, sqlgraph.NewFieldSpec(packagenode.FieldID, field.TypeInt))
	)
	if value, ok := pnc.mutation.GetType(); ok {
		_spec.SetField(packagenode.FieldType, field.TypeString, value)
		_node.Type = value
	}
	if nodes := pnc.mutation.NamespacesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   packagenode.NamespacesTable,
			Columns: []string{packagenode.NamespacesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(packagenamespace.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// PackageNodeCreateBulk is the builder for creating many PackageNode entities in bulk.
type PackageNodeCreateBulk struct {
	config
	builders []*PackageNodeCreate
}

// Save creates the PackageNode entities in the database.
func (pncb *PackageNodeCreateBulk) Save(ctx context.Context) ([]*PackageNode, error) {
	specs := make([]*sqlgraph.CreateSpec, len(pncb.builders))
	nodes := make([]*PackageNode, len(pncb.builders))
	mutators := make([]Mutator, len(pncb.builders))
	for i := range pncb.builders {
		func(i int, root context.Context) {
			builder := pncb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PackageNodeMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, pncb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, pncb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, pncb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (pncb *PackageNodeCreateBulk) SaveX(ctx context.Context) []*PackageNode {
	v, err := pncb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (pncb *PackageNodeCreateBulk) Exec(ctx context.Context) error {
	_, err := pncb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pncb *PackageNodeCreateBulk) ExecX(ctx context.Context) {
	if err := pncb.Exec(ctx); err != nil {
		panic(err)
	}
}
