// Code generated by ent, DO NOT EDIT.

package ent

import (
	"github.com/guacsec/guac/pkg/assembler/backends/ent/packagename"
	"github.com/guacsec/guac/pkg/assembler/backends/ent/packagetype"
	"github.com/guacsec/guac/pkg/assembler/backends/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	packagenameFields := schema.PackageName{}.Fields()
	_ = packagenameFields
	// packagenameDescName is the schema descriptor for name field.
	packagenameDescName := packagenameFields[1].Descriptor()
	// packagename.NameValidator is a validator for the "name" field. It is called by the builders before save.
	packagename.NameValidator = packagenameDescName.Validators[0].(func(string) error)
	packagetypeFields := schema.PackageType{}.Fields()
	_ = packagetypeFields
	// packagetypeDescType is the schema descriptor for type field.
	packagetypeDescType := packagetypeFields[0].Descriptor()
	// packagetype.TypeValidator is a validator for the "type" field. It is called by the builders before save.
	packagetype.TypeValidator = packagetypeDescType.Validators[0].(func(string) error)
}
