// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/guacsec/guac/pkg/assembler/backends/ent/artifact"
	"github.com/guacsec/guac/pkg/assembler/backends/ent/packageversion"
	"github.com/guacsec/guac/pkg/assembler/backends/ent/sbom"
)

// SBOMCreate is the builder for creating a SBOM entity.
type SBOMCreate struct {
	config
	mutation *SBOMMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetPackageID sets the "package_id" field.
func (sc *SBOMCreate) SetPackageID(i int) *SBOMCreate {
	sc.mutation.SetPackageID(i)
	return sc
}

// SetNillablePackageID sets the "package_id" field if the given value is not nil.
func (sc *SBOMCreate) SetNillablePackageID(i *int) *SBOMCreate {
	if i != nil {
		sc.SetPackageID(*i)
	}
	return sc
}

// SetArtifactID sets the "artifact_id" field.
func (sc *SBOMCreate) SetArtifactID(i int) *SBOMCreate {
	sc.mutation.SetArtifactID(i)
	return sc
}

// SetNillableArtifactID sets the "artifact_id" field if the given value is not nil.
func (sc *SBOMCreate) SetNillableArtifactID(i *int) *SBOMCreate {
	if i != nil {
		sc.SetArtifactID(*i)
	}
	return sc
}

// SetURI sets the "uri" field.
func (sc *SBOMCreate) SetURI(s string) *SBOMCreate {
	sc.mutation.SetURI(s)
	return sc
}

// SetAlgorithm sets the "algorithm" field.
func (sc *SBOMCreate) SetAlgorithm(s string) *SBOMCreate {
	sc.mutation.SetAlgorithm(s)
	return sc
}

// SetDigest sets the "digest" field.
func (sc *SBOMCreate) SetDigest(s string) *SBOMCreate {
	sc.mutation.SetDigest(s)
	return sc
}

// SetDownloadLocation sets the "downloadLocation" field.
func (sc *SBOMCreate) SetDownloadLocation(s string) *SBOMCreate {
	sc.mutation.SetDownloadLocation(s)
	return sc
}

// SetOrigin sets the "origin" field.
func (sc *SBOMCreate) SetOrigin(s string) *SBOMCreate {
	sc.mutation.SetOrigin(s)
	return sc
}

// SetCollector sets the "collector" field.
func (sc *SBOMCreate) SetCollector(s string) *SBOMCreate {
	sc.mutation.SetCollector(s)
	return sc
}

// SetPackage sets the "package" edge to the PackageVersion entity.
func (sc *SBOMCreate) SetPackage(p *PackageVersion) *SBOMCreate {
	return sc.SetPackageID(p.ID)
}

// SetArtifact sets the "artifact" edge to the Artifact entity.
func (sc *SBOMCreate) SetArtifact(a *Artifact) *SBOMCreate {
	return sc.SetArtifactID(a.ID)
}

// Mutation returns the SBOMMutation object of the builder.
func (sc *SBOMCreate) Mutation() *SBOMMutation {
	return sc.mutation
}

// Save creates the SBOM in the database.
func (sc *SBOMCreate) Save(ctx context.Context) (*SBOM, error) {
	return withHooks(ctx, sc.sqlSave, sc.mutation, sc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (sc *SBOMCreate) SaveX(ctx context.Context) *SBOM {
	v, err := sc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (sc *SBOMCreate) Exec(ctx context.Context) error {
	_, err := sc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (sc *SBOMCreate) ExecX(ctx context.Context) {
	if err := sc.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (sc *SBOMCreate) check() error {
	if _, ok := sc.mutation.URI(); !ok {
		return &ValidationError{Name: "uri", err: errors.New(`ent: missing required field "SBOM.uri"`)}
	}
	if _, ok := sc.mutation.Algorithm(); !ok {
		return &ValidationError{Name: "algorithm", err: errors.New(`ent: missing required field "SBOM.algorithm"`)}
	}
	if _, ok := sc.mutation.Digest(); !ok {
		return &ValidationError{Name: "digest", err: errors.New(`ent: missing required field "SBOM.digest"`)}
	}
	if _, ok := sc.mutation.DownloadLocation(); !ok {
		return &ValidationError{Name: "downloadLocation", err: errors.New(`ent: missing required field "SBOM.downloadLocation"`)}
	}
	if _, ok := sc.mutation.Origin(); !ok {
		return &ValidationError{Name: "origin", err: errors.New(`ent: missing required field "SBOM.origin"`)}
	}
	if _, ok := sc.mutation.Collector(); !ok {
		return &ValidationError{Name: "collector", err: errors.New(`ent: missing required field "SBOM.collector"`)}
	}
	return nil
}

func (sc *SBOMCreate) sqlSave(ctx context.Context) (*SBOM, error) {
	if err := sc.check(); err != nil {
		return nil, err
	}
	_node, _spec := sc.createSpec()
	if err := sqlgraph.CreateNode(ctx, sc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	sc.mutation.id = &_node.ID
	sc.mutation.done = true
	return _node, nil
}

func (sc *SBOMCreate) createSpec() (*SBOM, *sqlgraph.CreateSpec) {
	var (
		_node = &SBOM{config: sc.config}
		_spec = sqlgraph.NewCreateSpec(sbom.Table, sqlgraph.NewFieldSpec(sbom.FieldID, field.TypeInt))
	)
	_spec.OnConflict = sc.conflict
	if value, ok := sc.mutation.URI(); ok {
		_spec.SetField(sbom.FieldURI, field.TypeString, value)
		_node.URI = value
	}
	if value, ok := sc.mutation.Algorithm(); ok {
		_spec.SetField(sbom.FieldAlgorithm, field.TypeString, value)
		_node.Algorithm = value
	}
	if value, ok := sc.mutation.Digest(); ok {
		_spec.SetField(sbom.FieldDigest, field.TypeString, value)
		_node.Digest = value
	}
	if value, ok := sc.mutation.DownloadLocation(); ok {
		_spec.SetField(sbom.FieldDownloadLocation, field.TypeString, value)
		_node.DownloadLocation = value
	}
	if value, ok := sc.mutation.Origin(); ok {
		_spec.SetField(sbom.FieldOrigin, field.TypeString, value)
		_node.Origin = value
	}
	if value, ok := sc.mutation.Collector(); ok {
		_spec.SetField(sbom.FieldCollector, field.TypeString, value)
		_node.Collector = value
	}
	if nodes := sc.mutation.PackageIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   sbom.PackageTable,
			Columns: []string{sbom.PackageColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(packageversion.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.PackageID = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := sc.mutation.ArtifactIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   sbom.ArtifactTable,
			Columns: []string{sbom.ArtifactColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(artifact.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ArtifactID = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.SBOM.Create().
//		SetPackageID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.SBOMUpsert) {
//			SetPackageID(v+v).
//		}).
//		Exec(ctx)
func (sc *SBOMCreate) OnConflict(opts ...sql.ConflictOption) *SBOMUpsertOne {
	sc.conflict = opts
	return &SBOMUpsertOne{
		create: sc,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.SBOM.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (sc *SBOMCreate) OnConflictColumns(columns ...string) *SBOMUpsertOne {
	sc.conflict = append(sc.conflict, sql.ConflictColumns(columns...))
	return &SBOMUpsertOne{
		create: sc,
	}
}

type (
	// SBOMUpsertOne is the builder for "upsert"-ing
	//  one SBOM node.
	SBOMUpsertOne struct {
		create *SBOMCreate
	}

	// SBOMUpsert is the "OnConflict" setter.
	SBOMUpsert struct {
		*sql.UpdateSet
	}
)

// SetPackageID sets the "package_id" field.
func (u *SBOMUpsert) SetPackageID(v int) *SBOMUpsert {
	u.Set(sbom.FieldPackageID, v)
	return u
}

// UpdatePackageID sets the "package_id" field to the value that was provided on create.
func (u *SBOMUpsert) UpdatePackageID() *SBOMUpsert {
	u.SetExcluded(sbom.FieldPackageID)
	return u
}

// ClearPackageID clears the value of the "package_id" field.
func (u *SBOMUpsert) ClearPackageID() *SBOMUpsert {
	u.SetNull(sbom.FieldPackageID)
	return u
}

// SetArtifactID sets the "artifact_id" field.
func (u *SBOMUpsert) SetArtifactID(v int) *SBOMUpsert {
	u.Set(sbom.FieldArtifactID, v)
	return u
}

// UpdateArtifactID sets the "artifact_id" field to the value that was provided on create.
func (u *SBOMUpsert) UpdateArtifactID() *SBOMUpsert {
	u.SetExcluded(sbom.FieldArtifactID)
	return u
}

// ClearArtifactID clears the value of the "artifact_id" field.
func (u *SBOMUpsert) ClearArtifactID() *SBOMUpsert {
	u.SetNull(sbom.FieldArtifactID)
	return u
}

// SetURI sets the "uri" field.
func (u *SBOMUpsert) SetURI(v string) *SBOMUpsert {
	u.Set(sbom.FieldURI, v)
	return u
}

// UpdateURI sets the "uri" field to the value that was provided on create.
func (u *SBOMUpsert) UpdateURI() *SBOMUpsert {
	u.SetExcluded(sbom.FieldURI)
	return u
}

// SetAlgorithm sets the "algorithm" field.
func (u *SBOMUpsert) SetAlgorithm(v string) *SBOMUpsert {
	u.Set(sbom.FieldAlgorithm, v)
	return u
}

// UpdateAlgorithm sets the "algorithm" field to the value that was provided on create.
func (u *SBOMUpsert) UpdateAlgorithm() *SBOMUpsert {
	u.SetExcluded(sbom.FieldAlgorithm)
	return u
}

// SetDigest sets the "digest" field.
func (u *SBOMUpsert) SetDigest(v string) *SBOMUpsert {
	u.Set(sbom.FieldDigest, v)
	return u
}

// UpdateDigest sets the "digest" field to the value that was provided on create.
func (u *SBOMUpsert) UpdateDigest() *SBOMUpsert {
	u.SetExcluded(sbom.FieldDigest)
	return u
}

// SetDownloadLocation sets the "downloadLocation" field.
func (u *SBOMUpsert) SetDownloadLocation(v string) *SBOMUpsert {
	u.Set(sbom.FieldDownloadLocation, v)
	return u
}

// UpdateDownloadLocation sets the "downloadLocation" field to the value that was provided on create.
func (u *SBOMUpsert) UpdateDownloadLocation() *SBOMUpsert {
	u.SetExcluded(sbom.FieldDownloadLocation)
	return u
}

// SetOrigin sets the "origin" field.
func (u *SBOMUpsert) SetOrigin(v string) *SBOMUpsert {
	u.Set(sbom.FieldOrigin, v)
	return u
}

// UpdateOrigin sets the "origin" field to the value that was provided on create.
func (u *SBOMUpsert) UpdateOrigin() *SBOMUpsert {
	u.SetExcluded(sbom.FieldOrigin)
	return u
}

// SetCollector sets the "collector" field.
func (u *SBOMUpsert) SetCollector(v string) *SBOMUpsert {
	u.Set(sbom.FieldCollector, v)
	return u
}

// UpdateCollector sets the "collector" field to the value that was provided on create.
func (u *SBOMUpsert) UpdateCollector() *SBOMUpsert {
	u.SetExcluded(sbom.FieldCollector)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.SBOM.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *SBOMUpsertOne) UpdateNewValues() *SBOMUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.SBOM.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *SBOMUpsertOne) Ignore() *SBOMUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *SBOMUpsertOne) DoNothing() *SBOMUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the SBOMCreate.OnConflict
// documentation for more info.
func (u *SBOMUpsertOne) Update(set func(*SBOMUpsert)) *SBOMUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&SBOMUpsert{UpdateSet: update})
	}))
	return u
}

// SetPackageID sets the "package_id" field.
func (u *SBOMUpsertOne) SetPackageID(v int) *SBOMUpsertOne {
	return u.Update(func(s *SBOMUpsert) {
		s.SetPackageID(v)
	})
}

// UpdatePackageID sets the "package_id" field to the value that was provided on create.
func (u *SBOMUpsertOne) UpdatePackageID() *SBOMUpsertOne {
	return u.Update(func(s *SBOMUpsert) {
		s.UpdatePackageID()
	})
}

// ClearPackageID clears the value of the "package_id" field.
func (u *SBOMUpsertOne) ClearPackageID() *SBOMUpsertOne {
	return u.Update(func(s *SBOMUpsert) {
		s.ClearPackageID()
	})
}

// SetArtifactID sets the "artifact_id" field.
func (u *SBOMUpsertOne) SetArtifactID(v int) *SBOMUpsertOne {
	return u.Update(func(s *SBOMUpsert) {
		s.SetArtifactID(v)
	})
}

// UpdateArtifactID sets the "artifact_id" field to the value that was provided on create.
func (u *SBOMUpsertOne) UpdateArtifactID() *SBOMUpsertOne {
	return u.Update(func(s *SBOMUpsert) {
		s.UpdateArtifactID()
	})
}

// ClearArtifactID clears the value of the "artifact_id" field.
func (u *SBOMUpsertOne) ClearArtifactID() *SBOMUpsertOne {
	return u.Update(func(s *SBOMUpsert) {
		s.ClearArtifactID()
	})
}

// SetURI sets the "uri" field.
func (u *SBOMUpsertOne) SetURI(v string) *SBOMUpsertOne {
	return u.Update(func(s *SBOMUpsert) {
		s.SetURI(v)
	})
}

// UpdateURI sets the "uri" field to the value that was provided on create.
func (u *SBOMUpsertOne) UpdateURI() *SBOMUpsertOne {
	return u.Update(func(s *SBOMUpsert) {
		s.UpdateURI()
	})
}

// SetAlgorithm sets the "algorithm" field.
func (u *SBOMUpsertOne) SetAlgorithm(v string) *SBOMUpsertOne {
	return u.Update(func(s *SBOMUpsert) {
		s.SetAlgorithm(v)
	})
}

// UpdateAlgorithm sets the "algorithm" field to the value that was provided on create.
func (u *SBOMUpsertOne) UpdateAlgorithm() *SBOMUpsertOne {
	return u.Update(func(s *SBOMUpsert) {
		s.UpdateAlgorithm()
	})
}

// SetDigest sets the "digest" field.
func (u *SBOMUpsertOne) SetDigest(v string) *SBOMUpsertOne {
	return u.Update(func(s *SBOMUpsert) {
		s.SetDigest(v)
	})
}

// UpdateDigest sets the "digest" field to the value that was provided on create.
func (u *SBOMUpsertOne) UpdateDigest() *SBOMUpsertOne {
	return u.Update(func(s *SBOMUpsert) {
		s.UpdateDigest()
	})
}

// SetDownloadLocation sets the "downloadLocation" field.
func (u *SBOMUpsertOne) SetDownloadLocation(v string) *SBOMUpsertOne {
	return u.Update(func(s *SBOMUpsert) {
		s.SetDownloadLocation(v)
	})
}

// UpdateDownloadLocation sets the "downloadLocation" field to the value that was provided on create.
func (u *SBOMUpsertOne) UpdateDownloadLocation() *SBOMUpsertOne {
	return u.Update(func(s *SBOMUpsert) {
		s.UpdateDownloadLocation()
	})
}

// SetOrigin sets the "origin" field.
func (u *SBOMUpsertOne) SetOrigin(v string) *SBOMUpsertOne {
	return u.Update(func(s *SBOMUpsert) {
		s.SetOrigin(v)
	})
}

// UpdateOrigin sets the "origin" field to the value that was provided on create.
func (u *SBOMUpsertOne) UpdateOrigin() *SBOMUpsertOne {
	return u.Update(func(s *SBOMUpsert) {
		s.UpdateOrigin()
	})
}

// SetCollector sets the "collector" field.
func (u *SBOMUpsertOne) SetCollector(v string) *SBOMUpsertOne {
	return u.Update(func(s *SBOMUpsert) {
		s.SetCollector(v)
	})
}

// UpdateCollector sets the "collector" field to the value that was provided on create.
func (u *SBOMUpsertOne) UpdateCollector() *SBOMUpsertOne {
	return u.Update(func(s *SBOMUpsert) {
		s.UpdateCollector()
	})
}

// Exec executes the query.
func (u *SBOMUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for SBOMCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *SBOMUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *SBOMUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *SBOMUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// SBOMCreateBulk is the builder for creating many SBOM entities in bulk.
type SBOMCreateBulk struct {
	config
	builders []*SBOMCreate
	conflict []sql.ConflictOption
}

// Save creates the SBOM entities in the database.
func (scb *SBOMCreateBulk) Save(ctx context.Context) ([]*SBOM, error) {
	specs := make([]*sqlgraph.CreateSpec, len(scb.builders))
	nodes := make([]*SBOM, len(scb.builders))
	mutators := make([]Mutator, len(scb.builders))
	for i := range scb.builders {
		func(i int, root context.Context) {
			builder := scb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SBOMMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, scb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = scb.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, scb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, scb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (scb *SBOMCreateBulk) SaveX(ctx context.Context) []*SBOM {
	v, err := scb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (scb *SBOMCreateBulk) Exec(ctx context.Context) error {
	_, err := scb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (scb *SBOMCreateBulk) ExecX(ctx context.Context) {
	if err := scb.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.SBOM.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.SBOMUpsert) {
//			SetPackageID(v+v).
//		}).
//		Exec(ctx)
func (scb *SBOMCreateBulk) OnConflict(opts ...sql.ConflictOption) *SBOMUpsertBulk {
	scb.conflict = opts
	return &SBOMUpsertBulk{
		create: scb,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.SBOM.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (scb *SBOMCreateBulk) OnConflictColumns(columns ...string) *SBOMUpsertBulk {
	scb.conflict = append(scb.conflict, sql.ConflictColumns(columns...))
	return &SBOMUpsertBulk{
		create: scb,
	}
}

// SBOMUpsertBulk is the builder for "upsert"-ing
// a bulk of SBOM nodes.
type SBOMUpsertBulk struct {
	create *SBOMCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.SBOM.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *SBOMUpsertBulk) UpdateNewValues() *SBOMUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.SBOM.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *SBOMUpsertBulk) Ignore() *SBOMUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *SBOMUpsertBulk) DoNothing() *SBOMUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the SBOMCreateBulk.OnConflict
// documentation for more info.
func (u *SBOMUpsertBulk) Update(set func(*SBOMUpsert)) *SBOMUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&SBOMUpsert{UpdateSet: update})
	}))
	return u
}

// SetPackageID sets the "package_id" field.
func (u *SBOMUpsertBulk) SetPackageID(v int) *SBOMUpsertBulk {
	return u.Update(func(s *SBOMUpsert) {
		s.SetPackageID(v)
	})
}

// UpdatePackageID sets the "package_id" field to the value that was provided on create.
func (u *SBOMUpsertBulk) UpdatePackageID() *SBOMUpsertBulk {
	return u.Update(func(s *SBOMUpsert) {
		s.UpdatePackageID()
	})
}

// ClearPackageID clears the value of the "package_id" field.
func (u *SBOMUpsertBulk) ClearPackageID() *SBOMUpsertBulk {
	return u.Update(func(s *SBOMUpsert) {
		s.ClearPackageID()
	})
}

// SetArtifactID sets the "artifact_id" field.
func (u *SBOMUpsertBulk) SetArtifactID(v int) *SBOMUpsertBulk {
	return u.Update(func(s *SBOMUpsert) {
		s.SetArtifactID(v)
	})
}

// UpdateArtifactID sets the "artifact_id" field to the value that was provided on create.
func (u *SBOMUpsertBulk) UpdateArtifactID() *SBOMUpsertBulk {
	return u.Update(func(s *SBOMUpsert) {
		s.UpdateArtifactID()
	})
}

// ClearArtifactID clears the value of the "artifact_id" field.
func (u *SBOMUpsertBulk) ClearArtifactID() *SBOMUpsertBulk {
	return u.Update(func(s *SBOMUpsert) {
		s.ClearArtifactID()
	})
}

// SetURI sets the "uri" field.
func (u *SBOMUpsertBulk) SetURI(v string) *SBOMUpsertBulk {
	return u.Update(func(s *SBOMUpsert) {
		s.SetURI(v)
	})
}

// UpdateURI sets the "uri" field to the value that was provided on create.
func (u *SBOMUpsertBulk) UpdateURI() *SBOMUpsertBulk {
	return u.Update(func(s *SBOMUpsert) {
		s.UpdateURI()
	})
}

// SetAlgorithm sets the "algorithm" field.
func (u *SBOMUpsertBulk) SetAlgorithm(v string) *SBOMUpsertBulk {
	return u.Update(func(s *SBOMUpsert) {
		s.SetAlgorithm(v)
	})
}

// UpdateAlgorithm sets the "algorithm" field to the value that was provided on create.
func (u *SBOMUpsertBulk) UpdateAlgorithm() *SBOMUpsertBulk {
	return u.Update(func(s *SBOMUpsert) {
		s.UpdateAlgorithm()
	})
}

// SetDigest sets the "digest" field.
func (u *SBOMUpsertBulk) SetDigest(v string) *SBOMUpsertBulk {
	return u.Update(func(s *SBOMUpsert) {
		s.SetDigest(v)
	})
}

// UpdateDigest sets the "digest" field to the value that was provided on create.
func (u *SBOMUpsertBulk) UpdateDigest() *SBOMUpsertBulk {
	return u.Update(func(s *SBOMUpsert) {
		s.UpdateDigest()
	})
}

// SetDownloadLocation sets the "downloadLocation" field.
func (u *SBOMUpsertBulk) SetDownloadLocation(v string) *SBOMUpsertBulk {
	return u.Update(func(s *SBOMUpsert) {
		s.SetDownloadLocation(v)
	})
}

// UpdateDownloadLocation sets the "downloadLocation" field to the value that was provided on create.
func (u *SBOMUpsertBulk) UpdateDownloadLocation() *SBOMUpsertBulk {
	return u.Update(func(s *SBOMUpsert) {
		s.UpdateDownloadLocation()
	})
}

// SetOrigin sets the "origin" field.
func (u *SBOMUpsertBulk) SetOrigin(v string) *SBOMUpsertBulk {
	return u.Update(func(s *SBOMUpsert) {
		s.SetOrigin(v)
	})
}

// UpdateOrigin sets the "origin" field to the value that was provided on create.
func (u *SBOMUpsertBulk) UpdateOrigin() *SBOMUpsertBulk {
	return u.Update(func(s *SBOMUpsert) {
		s.UpdateOrigin()
	})
}

// SetCollector sets the "collector" field.
func (u *SBOMUpsertBulk) SetCollector(v string) *SBOMUpsertBulk {
	return u.Update(func(s *SBOMUpsert) {
		s.SetCollector(v)
	})
}

// UpdateCollector sets the "collector" field to the value that was provided on create.
func (u *SBOMUpsertBulk) UpdateCollector() *SBOMUpsertBulk {
	return u.Update(func(s *SBOMUpsert) {
		s.UpdateCollector()
	})
}

// Exec executes the query.
func (u *SBOMUpsertBulk) Exec(ctx context.Context) error {
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the SBOMCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for SBOMCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *SBOMUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
