// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/guacsec/guac/pkg/assembler/backends/ent/predicate"
	"github.com/guacsec/guac/pkg/assembler/backends/ent/vulnequal"
	"github.com/guacsec/guac/pkg/assembler/backends/ent/vulnerabilityid"
)

// VulnEqualUpdate is the builder for updating VulnEqual entities.
type VulnEqualUpdate struct {
	config
	hooks    []Hook
	mutation *VulnEqualMutation
}

// Where appends a list predicates to the VulnEqualUpdate builder.
func (_u *VulnEqualUpdate) Where(ps ...predicate.VulnEqual) *VulnEqualUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetVulnID sets the "vuln_id" field.
func (_u *VulnEqualUpdate) SetVulnID(v uuid.UUID) *VulnEqualUpdate {
	_u.mutation.SetVulnID(v)
	return _u
}

// SetNillableVulnID sets the "vuln_id" field if the given value is not nil.
func (_u *VulnEqualUpdate) SetNillableVulnID(v *uuid.UUID) *VulnEqualUpdate {
	if v != nil {
		_u.SetVulnID(*v)
	}
	return _u
}

// SetEqualVulnID sets the "equal_vuln_id" field.
func (_u *VulnEqualUpdate) SetEqualVulnID(v uuid.UUID) *VulnEqualUpdate {
	_u.mutation.SetEqualVulnID(v)
	return _u
}

// SetNillableEqualVulnID sets the "equal_vuln_id" field if the given value is not nil.
func (_u *VulnEqualUpdate) SetNillableEqualVulnID(v *uuid.UUID) *VulnEqualUpdate {
	if v != nil {
		_u.SetEqualVulnID(*v)
	}
	return _u
}

// SetJustification sets the "justification" field.
func (_u *VulnEqualUpdate) SetJustification(v string) *VulnEqualUpdate {
	_u.mutation.SetJustification(v)
	return _u
}

// SetNillableJustification sets the "justification" field if the given value is not nil.
func (_u *VulnEqualUpdate) SetNillableJustification(v *string) *VulnEqualUpdate {
	if v != nil {
		_u.SetJustification(*v)
	}
	return _u
}

// SetOrigin sets the "origin" field.
func (_u *VulnEqualUpdate) SetOrigin(v string) *VulnEqualUpdate {
	_u.mutation.SetOrigin(v)
	return _u
}

// SetNillableOrigin sets the "origin" field if the given value is not nil.
func (_u *VulnEqualUpdate) SetNillableOrigin(v *string) *VulnEqualUpdate {
	if v != nil {
		_u.SetOrigin(*v)
	}
	return _u
}

// SetCollector sets the "collector" field.
func (_u *VulnEqualUpdate) SetCollector(v string) *VulnEqualUpdate {
	_u.mutation.SetCollector(v)
	return _u
}

// SetNillableCollector sets the "collector" field if the given value is not nil.
func (_u *VulnEqualUpdate) SetNillableCollector(v *string) *VulnEqualUpdate {
	if v != nil {
		_u.SetCollector(*v)
	}
	return _u
}

// SetDocumentRef sets the "document_ref" field.
func (_u *VulnEqualUpdate) SetDocumentRef(v string) *VulnEqualUpdate {
	_u.mutation.SetDocumentRef(v)
	return _u
}

// SetNillableDocumentRef sets the "document_ref" field if the given value is not nil.
func (_u *VulnEqualUpdate) SetNillableDocumentRef(v *string) *VulnEqualUpdate {
	if v != nil {
		_u.SetDocumentRef(*v)
	}
	return _u
}

// SetVulnerabilitiesHash sets the "vulnerabilities_hash" field.
func (_u *VulnEqualUpdate) SetVulnerabilitiesHash(v string) *VulnEqualUpdate {
	_u.mutation.SetVulnerabilitiesHash(v)
	return _u
}

// SetNillableVulnerabilitiesHash sets the "vulnerabilities_hash" field if the given value is not nil.
func (_u *VulnEqualUpdate) SetNillableVulnerabilitiesHash(v *string) *VulnEqualUpdate {
	if v != nil {
		_u.SetVulnerabilitiesHash(*v)
	}
	return _u
}

// SetVulnerabilityAID sets the "vulnerability_a" edge to the VulnerabilityID entity by ID.
func (_u *VulnEqualUpdate) SetVulnerabilityAID(id uuid.UUID) *VulnEqualUpdate {
	_u.mutation.SetVulnerabilityAID(id)
	return _u
}

// SetVulnerabilityA sets the "vulnerability_a" edge to the VulnerabilityID entity.
func (_u *VulnEqualUpdate) SetVulnerabilityA(v *VulnerabilityID) *VulnEqualUpdate {
	return _u.SetVulnerabilityAID(v.ID)
}

// SetVulnerabilityBID sets the "vulnerability_b" edge to the VulnerabilityID entity by ID.
func (_u *VulnEqualUpdate) SetVulnerabilityBID(id uuid.UUID) *VulnEqualUpdate {
	_u.mutation.SetVulnerabilityBID(id)
	return _u
}

// SetVulnerabilityB sets the "vulnerability_b" edge to the VulnerabilityID entity.
func (_u *VulnEqualUpdate) SetVulnerabilityB(v *VulnerabilityID) *VulnEqualUpdate {
	return _u.SetVulnerabilityBID(v.ID)
}

// Mutation returns the VulnEqualMutation object of the builder.
func (_u *VulnEqualUpdate) Mutation() *VulnEqualMutation {
	return _u.mutation
}

// ClearVulnerabilityA clears the "vulnerability_a" edge to the VulnerabilityID entity.
func (_u *VulnEqualUpdate) ClearVulnerabilityA() *VulnEqualUpdate {
	_u.mutation.ClearVulnerabilityA()
	return _u
}

// ClearVulnerabilityB clears the "vulnerability_b" edge to the VulnerabilityID entity.
func (_u *VulnEqualUpdate) ClearVulnerabilityB() *VulnEqualUpdate {
	_u.mutation.ClearVulnerabilityB()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *VulnEqualUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *VulnEqualUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *VulnEqualUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *VulnEqualUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *VulnEqualUpdate) check() error {
	if _u.mutation.VulnerabilityACleared() && len(_u.mutation.VulnerabilityAIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "VulnEqual.vulnerability_a"`)
	}
	if _u.mutation.VulnerabilityBCleared() && len(_u.mutation.VulnerabilityBIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "VulnEqual.vulnerability_b"`)
	}
	return nil
}

func (_u *VulnEqualUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(vulnequal.Table, vulnequal.Columns, sqlgraph.NewFieldSpec(vulnequal.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Justification(); ok {
		_spec.SetField(vulnequal.FieldJustification, field.TypeString, value)
	}
	if value, ok := _u.mutation.Origin(); ok {
		_spec.SetField(vulnequal.FieldOrigin, field.TypeString, value)
	}
	if value, ok := _u.mutation.Collector(); ok {
		_spec.SetField(vulnequal.FieldCollector, field.TypeString, value)
	}
	if value, ok := _u.mutation.DocumentRef(); ok {
		_spec.SetField(vulnequal.FieldDocumentRef, field.TypeString, value)
	}
	if value, ok := _u.mutation.VulnerabilitiesHash(); ok {
		_spec.SetField(vulnequal.FieldVulnerabilitiesHash, field.TypeString, value)
	}
	if _u.mutation.VulnerabilityACleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   vulnequal.VulnerabilityATable,
			Columns: []string{vulnequal.VulnerabilityAColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(vulnerabilityid.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.VulnerabilityAIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   vulnequal.VulnerabilityATable,
			Columns: []string{vulnequal.VulnerabilityAColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(vulnerabilityid.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.VulnerabilityBCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   vulnequal.VulnerabilityBTable,
			Columns: []string{vulnequal.VulnerabilityBColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(vulnerabilityid.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.VulnerabilityBIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   vulnequal.VulnerabilityBTable,
			Columns: []string{vulnequal.VulnerabilityBColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(vulnerabilityid.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{vulnequal.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// VulnEqualUpdateOne is the builder for updating a single VulnEqual entity.
type VulnEqualUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *VulnEqualMutation
}

// SetVulnID sets the "vuln_id" field.
func (_u *VulnEqualUpdateOne) SetVulnID(v uuid.UUID) *VulnEqualUpdateOne {
	_u.mutation.SetVulnID(v)
	return _u
}

// SetNillableVulnID sets the "vuln_id" field if the given value is not nil.
func (_u *VulnEqualUpdateOne) SetNillableVulnID(v *uuid.UUID) *VulnEqualUpdateOne {
	if v != nil {
		_u.SetVulnID(*v)
	}
	return _u
}

// SetEqualVulnID sets the "equal_vuln_id" field.
func (_u *VulnEqualUpdateOne) SetEqualVulnID(v uuid.UUID) *VulnEqualUpdateOne {
	_u.mutation.SetEqualVulnID(v)
	return _u
}

// SetNillableEqualVulnID sets the "equal_vuln_id" field if the given value is not nil.
func (_u *VulnEqualUpdateOne) SetNillableEqualVulnID(v *uuid.UUID) *VulnEqualUpdateOne {
	if v != nil {
		_u.SetEqualVulnID(*v)
	}
	return _u
}

// SetJustification sets the "justification" field.
func (_u *VulnEqualUpdateOne) SetJustification(v string) *VulnEqualUpdateOne {
	_u.mutation.SetJustification(v)
	return _u
}

// SetNillableJustification sets the "justification" field if the given value is not nil.
func (_u *VulnEqualUpdateOne) SetNillableJustification(v *string) *VulnEqualUpdateOne {
	if v != nil {
		_u.SetJustification(*v)
	}
	return _u
}

// SetOrigin sets the "origin" field.
func (_u *VulnEqualUpdateOne) SetOrigin(v string) *VulnEqualUpdateOne {
	_u.mutation.SetOrigin(v)
	return _u
}

// SetNillableOrigin sets the "origin" field if the given value is not nil.
func (_u *VulnEqualUpdateOne) SetNillableOrigin(v *string) *VulnEqualUpdateOne {
	if v != nil {
		_u.SetOrigin(*v)
	}
	return _u
}

// SetCollector sets the "collector" field.
func (_u *VulnEqualUpdateOne) SetCollector(v string) *VulnEqualUpdateOne {
	_u.mutation.SetCollector(v)
	return _u
}

// SetNillableCollector sets the "collector" field if the given value is not nil.
func (_u *VulnEqualUpdateOne) SetNillableCollector(v *string) *VulnEqualUpdateOne {
	if v != nil {
		_u.SetCollector(*v)
	}
	return _u
}

// SetDocumentRef sets the "document_ref" field.
func (_u *VulnEqualUpdateOne) SetDocumentRef(v string) *VulnEqualUpdateOne {
	_u.mutation.SetDocumentRef(v)
	return _u
}

// SetNillableDocumentRef sets the "document_ref" field if the given value is not nil.
func (_u *VulnEqualUpdateOne) SetNillableDocumentRef(v *string) *VulnEqualUpdateOne {
	if v != nil {
		_u.SetDocumentRef(*v)
	}
	return _u
}

// SetVulnerabilitiesHash sets the "vulnerabilities_hash" field.
func (_u *VulnEqualUpdateOne) SetVulnerabilitiesHash(v string) *VulnEqualUpdateOne {
	_u.mutation.SetVulnerabilitiesHash(v)
	return _u
}

// SetNillableVulnerabilitiesHash sets the "vulnerabilities_hash" field if the given value is not nil.
func (_u *VulnEqualUpdateOne) SetNillableVulnerabilitiesHash(v *string) *VulnEqualUpdateOne {
	if v != nil {
		_u.SetVulnerabilitiesHash(*v)
	}
	return _u
}

// SetVulnerabilityAID sets the "vulnerability_a" edge to the VulnerabilityID entity by ID.
func (_u *VulnEqualUpdateOne) SetVulnerabilityAID(id uuid.UUID) *VulnEqualUpdateOne {
	_u.mutation.SetVulnerabilityAID(id)
	return _u
}

// SetVulnerabilityA sets the "vulnerability_a" edge to the VulnerabilityID entity.
func (_u *VulnEqualUpdateOne) SetVulnerabilityA(v *VulnerabilityID) *VulnEqualUpdateOne {
	return _u.SetVulnerabilityAID(v.ID)
}

// SetVulnerabilityBID sets the "vulnerability_b" edge to the VulnerabilityID entity by ID.
func (_u *VulnEqualUpdateOne) SetVulnerabilityBID(id uuid.UUID) *VulnEqualUpdateOne {
	_u.mutation.SetVulnerabilityBID(id)
	return _u
}

// SetVulnerabilityB sets the "vulnerability_b" edge to the VulnerabilityID entity.
func (_u *VulnEqualUpdateOne) SetVulnerabilityB(v *VulnerabilityID) *VulnEqualUpdateOne {
	return _u.SetVulnerabilityBID(v.ID)
}

// Mutation returns the VulnEqualMutation object of the builder.
func (_u *VulnEqualUpdateOne) Mutation() *VulnEqualMutation {
	return _u.mutation
}

// ClearVulnerabilityA clears the "vulnerability_a" edge to the VulnerabilityID entity.
func (_u *VulnEqualUpdateOne) ClearVulnerabilityA() *VulnEqualUpdateOne {
	_u.mutation.ClearVulnerabilityA()
	return _u
}

// ClearVulnerabilityB clears the "vulnerability_b" edge to the VulnerabilityID entity.
func (_u *VulnEqualUpdateOne) ClearVulnerabilityB() *VulnEqualUpdateOne {
	_u.mutation.ClearVulnerabilityB()
	return _u
}

// Where appends a list predicates to the VulnEqualUpdate builder.
func (_u *VulnEqualUpdateOne) Where(ps ...predicate.VulnEqual) *VulnEqualUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *VulnEqualUpdateOne) Select(field string, fields ...string) *VulnEqualUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated VulnEqual entity.
func (_u *VulnEqualUpdateOne) Save(ctx context.Context) (*VulnEqual, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *VulnEqualUpdateOne) SaveX(ctx context.Context) *VulnEqual {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *VulnEqualUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *VulnEqualUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *VulnEqualUpdateOne) check() error {
	if _u.mutation.VulnerabilityACleared() && len(_u.mutation.VulnerabilityAIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "VulnEqual.vulnerability_a"`)
	}
	if _u.mutation.VulnerabilityBCleared() && len(_u.mutation.VulnerabilityBIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "VulnEqual.vulnerability_b"`)
	}
	return nil
}

func (_u *VulnEqualUpdateOne) sqlSave(ctx context.Context) (_node *VulnEqual, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(vulnequal.Table, vulnequal.Columns, sqlgraph.NewFieldSpec(vulnequal.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "VulnEqual.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, vulnequal.FieldID)
		for _, f := range fields {
			if !vulnequal.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != vulnequal.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Justification(); ok {
		_spec.SetField(vulnequal.FieldJustification, field.TypeString, value)
	}
	if value, ok := _u.mutation.Origin(); ok {
		_spec.SetField(vulnequal.FieldOrigin, field.TypeString, value)
	}
	if value, ok := _u.mutation.Collector(); ok {
		_spec.SetField(vulnequal.FieldCollector, field.TypeString, value)
	}
	if value, ok := _u.mutation.DocumentRef(); ok {
		_spec.SetField(vulnequal.FieldDocumentRef, field.TypeString, value)
	}
	if value, ok := _u.mutation.VulnerabilitiesHash(); ok {
		_spec.SetField(vulnequal.FieldVulnerabilitiesHash, field.TypeString, value)
	}
	if _u.mutation.VulnerabilityACleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   vulnequal.VulnerabilityATable,
			Columns: []string{vulnequal.VulnerabilityAColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(vulnerabilityid.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.VulnerabilityAIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   vulnequal.VulnerabilityATable,
			Columns: []string{vulnequal.VulnerabilityAColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(vulnerabilityid.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.VulnerabilityBCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   vulnequal.VulnerabilityBTable,
			Columns: []string{vulnequal.VulnerabilityBColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(vulnerabilityid.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.VulnerabilityBIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   vulnequal.VulnerabilityBTable,
			Columns: []string{vulnequal.VulnerabilityBColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(vulnerabilityid.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &VulnEqual{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{vulnequal.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
