nats:
  image: nats:alpine

  #limits:
  #  maxPayload: "64MB"

  jetstream:
    enabled: true

    memStorage:
      enabled: true
      size: "128MB"
  #    size: "1Gi"

    fileStorage:
      enabled: false

cluster:
  enabled: false
