version: "3.8"

services:

  graphql:
    image: $GUAC_IMAGE
    command: "/opt/guac/guacgql --gql-debug"
    working_dir: /guac
    restart: on-failure
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:8080"]
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 5s

  collectsub:
    image: $GUAC_IMAGE
    command: "/opt/guac/guaccsub"
    working_dir: /guac
    restart: on-failure
    ports:
      - "2782:2782"
    depends_on:
    healthcheck:
      test: [ "CMD", "wget", "--spider", "http://localhost:2782" ]
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 5s

  depsdev-collector:
    image: $GUAC_IMAGE
    command: "/opt/guac/guacone collect deps_dev -p --csub-addr=collectsub:2782 --gql-addr=http://graphql:8080/query"
    working_dir: /guac
    restart: on-failure
    environment:
      - DEPS_DEV_APIKEY
    depends_on:
      collectsub:
        condition: service_healthy
      graphql:
        condition: service_healthy

  osv-certifier:
    image: $GUAC_IMAGE
    command: "/opt/guac/guacone certifier osv -p --csub-addr=collectsub:2782 --gql-addr=http://graphql:8080/query"
    working_dir: /guac
    restart: on-failure
    depends_on:
      collectsub:
        condition: service_healthy
      graphql:
        condition: service_healthy
