package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.25

import (
	"context"

	"github.com/guacsec/guac/pkg/assembler/graphql/model"
)

// Connected is the resolver for the connected field.
func (r *queryResolver) Connected(ctx context.Context, subject model.PackageSourceArtifactOsvCveOrGhsaFilter, maxPathLength int) (*model.EvidenceTrees, error) {
	return r.Backend.Connected(ctx, subject, maxPathLength)
}
