//
// Copyright 2026 The GUAC Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v5.26.1
// source: pkg/ingestor/ingestapi/ingest.proto

package ingestapi

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Status int32

const (
	Status_PENDING     Status = 0
	Status_IN_PROGRESS Status = 1
	Status_SUCCESS     Status = 2
	Status_FAILED      Status = 3
)

// Enum value maps for Status.
var (
	Status_name = map[int32]string{
		0: "PENDING",
		1: "IN_PROGRESS",
		2: "SUCCESS",
		3: "FAILED",
	}
	Status_value = map[string]int32{
		"PENDING":     0,
		"IN_PROGRESS": 1,
		"SUCCESS":     2,
		"FAILED":      3,
	}
)

func (x Status) Enum() *Status {
	p := new(Status)
	*p = x
	return p
}

func (x Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_ingestor_ingestapi_ingest_proto_enumTypes[0].Descriptor()
}

func (Status) Type() protoreflect.EnumType {
	return &file_pkg_ingestor_ingestapi_ingest_proto_enumTypes[0]
}

func (x Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status.Descriptor instead.
func (Status) EnumDescriptor() ([]byte, []int) {
	return file_pkg_ingestor_ingestapi_ingest_proto_rawDescGZIP(), []int{0}
}

// DocumentMetaData describes where the document came from. It maps onto
// processor.SourceInformation and must be the first message on the stream.
type DocumentMetaData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CollectorInformation string `protobuf:"bytes,1,opt,name=collectorInformation,proto3" json:"collectorInformation,omitempty"`
	SourceInformation    string `protobuf:"bytes,2,opt,name=sourceInformation,proto3" json:"sourceInformation,omitempty"`
}

func (x *DocumentMetaData) Reset() {
	*x = DocumentMetaData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_ingestor_ingestapi_ingest_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DocumentMetaData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DocumentMetaData) ProtoMessage() {}

func (x *DocumentMetaData) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_ingestor_ingestapi_ingest_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DocumentMetaData.ProtoReflect.Descriptor instead.
func (*DocumentMetaData) Descriptor() ([]byte, []int) {
	return file_pkg_ingestor_ingestapi_ingest_proto_rawDescGZIP(), []int{0}
}

func (x *DocumentMetaData) GetCollectorInformation() string {
	if x != nil {
		return x.CollectorInformation
	}
	return ""
}

func (x *DocumentMetaData) GetSourceInformation() string {
	if x != nil {
		return x.SourceInformation
	}
	return ""
}

// Document carries one chunk of the document body. Chunks are concatenated in
// the order they are received, so a client must not interleave streams.
type Document struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Content []byte `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
}

func (x *Document) Reset() {
	*x = Document{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_ingestor_ingestapi_ingest_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Document) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Document) ProtoMessage() {}

func (x *Document) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_ingestor_ingestapi_ingest_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Document.ProtoReflect.Descriptor instead.
func (*Document) Descriptor() ([]byte, []int) {
	return file_pkg_ingestor_ingestapi_ingest_proto_rawDescGZIP(), []int{1}
}

func (x *Document) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

type DocumentIngestRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Request:
	//
	//	*DocumentIngestRequest_Metadata
	//	*DocumentIngestRequest_Doc
	Request isDocumentIngestRequest_Request `protobuf_oneof:"request"`
}

func (x *DocumentIngestRequest) Reset() {
	*x = DocumentIngestRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_ingestor_ingestapi_ingest_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DocumentIngestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DocumentIngestRequest) ProtoMessage() {}

func (x *DocumentIngestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_ingestor_ingestapi_ingest_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DocumentIngestRequest.ProtoReflect.Descriptor instead.
func (*DocumentIngestRequest) Descriptor() ([]byte, []int) {
	return file_pkg_ingestor_ingestapi_ingest_proto_rawDescGZIP(), []int{2}
}

func (m *DocumentIngestRequest) GetRequest() isDocumentIngestRequest_Request {
	if m != nil {
		return m.Request
	}
	return nil
}

func (x *DocumentIngestRequest) GetMetadata() *DocumentMetaData {
	if x, ok := x.GetRequest().(*DocumentIngestRequest_Metadata); ok {
		return x.Metadata
	}
	return nil
}

func (x *DocumentIngestRequest) GetDoc() *Document {
	if x, ok := x.GetRequest().(*DocumentIngestRequest_Doc); ok {
		return x.Doc
	}
	return nil
}

type isDocumentIngestRequest_Request interface {
	isDocumentIngestRequest_Request()
}

type DocumentIngestRequest_Metadata struct {
	Metadata *DocumentMetaData `protobuf:"bytes,1,opt,name=metadata,proto3,oneof"`
}

type DocumentIngestRequest_Doc struct {
	Doc *Document `protobuf:"bytes,2,opt,name=doc,proto3,oneof"`
}

func (*DocumentIngestRequest_Metadata) isDocumentIngestRequest_Request() {}

func (*DocumentIngestRequest_Doc) isDocumentIngestRequest_Request() {}

type DocumentIngestResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status Status `protobuf:"varint,1,opt,name=status,proto3,enum=guacsec.guac.ingestor.schema.Status" json:"status,omitempty"`
	// documentRef is the content addressed key of the document, matching the
	// key the blob store path would use. Clients can correlate it with server
	// side logs, which tag every line with the same value.
	DocumentRef string `protobuf:"bytes,2,opt,name=documentRef,proto3" json:"documentRef,omitempty"`
}

func (x *DocumentIngestResponse) Reset() {
	*x = DocumentIngestResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_ingestor_ingestapi_ingest_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DocumentIngestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DocumentIngestResponse) ProtoMessage() {}

func (x *DocumentIngestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_ingestor_ingestapi_ingest_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DocumentIngestResponse.ProtoReflect.Descriptor instead.
func (*DocumentIngestResponse) Descriptor() ([]byte, []int) {
	return file_pkg_ingestor_ingestapi_ingest_proto_rawDescGZIP(), []int{3}
}

func (x *DocumentIngestResponse) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_PENDING
}

func (x *DocumentIngestResponse) GetDocumentRef() string {
	if x != nil {
		return x.DocumentRef
	}
	return ""
}

var File_pkg_ingestor_ingestapi_ingest_proto protoreflect.FileDescriptor

var file_pkg_ingestor_ingestapi_ingest_proto_rawDesc = []byte{
	0x0a, 0x23, 0x70, 0x6b, 0x67, 0x2f, 0x69, 0x6e, 0x67, 0x65, 0x73, 0x74, 0x6f, 0x72, 0x2f, 0x69,
	0x6e, 0x67, 0x65, 0x73, 0x74, 0x61, 0x70, 0x69, 0x2f, 0x69, 0x6e, 0x67, 0x65, 0x73, 0x74, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x1c, 0x67, 0x75, 0x61, 0x63, 0x73, 0x65, 0x63, 0x2e, 0x67,
	0x75, 0x61, 0x63, 0x2e, 0x69, 0x6e, 0x67, 0x65, 0x73, 0x74, 0x6f, 0x72, 0x2e, 0x73, 0x63, 0x68,
	0x65, 0x6d, 0x61, 0x22, 0x74, 0x0a, 0x10, 0x44, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x4d,
	0x65, 0x74, 0x61, 0x44, 0x61, 0x74, 0x61, 0x12, 0x32, 0x0a, 0x14, 0x63, 0x6f, 0x6c, 0x6c, 0x65,
	0x63, 0x74, 0x6f, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x14, 0x63, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x6f, 0x72,
	0x49, 0x6e, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x2c, 0x0a, 0x11, 0x73,
	0x6f, 0x75, 0x72, 0x63, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x11, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x49, 0x6e,
	0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x24, 0x0a, 0x08, 0x44, 0x6f, 0x63,
	0x75, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x22,
	0xac, 0x01, 0x0a, 0x15, 0x44, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x6e, 0x67, 0x65,
	0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x4c, 0x0a, 0x08, 0x6d, 0x65, 0x74,
	0x61, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2e, 0x2e, 0x67, 0x75,
	0x61, 0x63, 0x73, 0x65, 0x63, 0x2e, 0x67, 0x75, 0x61, 0x63, 0x2e, 0x69, 0x6e, 0x67, 0x65, 0x73,
	0x74, 0x6f, 0x72, 0x2e, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x2e, 0x44, 0x6f, 0x63, 0x75, 0x6d,
	0x65, 0x6e, 0x74, 0x4d, 0x65, 0x74, 0x61, 0x44, 0x61, 0x74, 0x61, 0x48, 0x00, 0x52, 0x08, 0x6d,
	0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x12, 0x3a, 0x0a, 0x03, 0x64, 0x6f, 0x63, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x26, 0x2e, 0x67, 0x75, 0x61, 0x63, 0x73, 0x65, 0x63, 0x2e, 0x67,
	0x75, 0x61, 0x63, 0x2e, 0x69, 0x6e, 0x67, 0x65, 0x73, 0x74, 0x6f, 0x72, 0x2e, 0x73, 0x63, 0x68,
	0x65, 0x6d, 0x61, 0x2e, 0x44, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x48, 0x00, 0x52, 0x03,
	0x64, 0x6f, 0x63, 0x42, 0x09, 0x0a, 0x07, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x78,
	0x0a, 0x16, 0x44, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x6e, 0x67, 0x65, 0x73, 0x74,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3c, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x24, 0x2e, 0x67, 0x75, 0x61, 0x63, 0x73,
	0x65, 0x63, 0x2e, 0x67, 0x75, 0x61, 0x63, 0x2e, 0x69, 0x6e, 0x67, 0x65, 0x73, 0x74, 0x6f, 0x72,
	0x2e, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x6f, 0x63, 0x75, 0x6d, 0x65,
	0x6e, 0x74, 0x52, 0x65, 0x66, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x6f, 0x63,
	0x75, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x66, 0x2a, 0x3f, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x12, 0x0b, 0x0a, 0x07, 0x50, 0x45, 0x4e, 0x44, 0x49, 0x4e, 0x47, 0x10, 0x00, 0x12,
	0x0f, 0x0a, 0x0b, 0x49, 0x4e, 0x5f, 0x50, 0x52, 0x4f, 0x47, 0x52, 0x45, 0x53, 0x53, 0x10, 0x01,
	0x12, 0x0b, 0x0a, 0x07, 0x53, 0x55, 0x43, 0x43, 0x45, 0x53, 0x53, 0x10, 0x02, 0x12, 0x0a, 0x0a,
	0x06, 0x46, 0x41, 0x49, 0x4c, 0x45, 0x44, 0x10, 0x03, 0x32, 0x96, 0x01, 0x0a, 0x15, 0x44, 0x6f,
	0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x6e, 0x67, 0x65, 0x73, 0x74, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x12, 0x7d, 0x0a, 0x0e, 0x49, 0x6e, 0x67, 0x65, 0x73, 0x74, 0x44, 0x6f, 0x63,
	0x75, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x33, 0x2e, 0x67, 0x75, 0x61, 0x63, 0x73, 0x65, 0x63, 0x2e,
	0x67, 0x75, 0x61, 0x63, 0x2e, 0x69, 0x6e, 0x67, 0x65, 0x73, 0x74, 0x6f, 0x72, 0x2e, 0x73, 0x63,
	0x68, 0x65, 0x6d, 0x61, 0x2e, 0x44, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x6e, 0x67,
	0x65, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x34, 0x2e, 0x67, 0x75, 0x61,
	0x63, 0x73, 0x65, 0x63, 0x2e, 0x67, 0x75, 0x61, 0x63, 0x2e, 0x69, 0x6e, 0x67, 0x65, 0x73, 0x74,
	0x6f, 0x72, 0x2e, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x2e, 0x44, 0x6f, 0x63, 0x75, 0x6d, 0x65,
	0x6e, 0x74, 0x49, 0x6e, 0x67, 0x65, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x28, 0x01, 0x42, 0x30, 0x5a, 0x2e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x67, 0x75, 0x61, 0x63, 0x73, 0x65, 0x63, 0x2f, 0x67, 0x75, 0x61, 0x63, 0x2f, 0x70, 0x6b,
	0x67, 0x2f, 0x69, 0x6e, 0x67, 0x65, 0x73, 0x74, 0x6f, 0x72, 0x2f, 0x69, 0x6e, 0x67, 0x65, 0x73,
	0x74, 0x61, 0x70, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pkg_ingestor_ingestapi_ingest_proto_rawDescOnce sync.Once
	file_pkg_ingestor_ingestapi_ingest_proto_rawDescData = file_pkg_ingestor_ingestapi_ingest_proto_rawDesc
)

func file_pkg_ingestor_ingestapi_ingest_proto_rawDescGZIP() []byte {
	file_pkg_ingestor_ingestapi_ingest_proto_rawDescOnce.Do(func() {
		file_pkg_ingestor_ingestapi_ingest_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_ingestor_ingestapi_ingest_proto_rawDescData)
	})
	return file_pkg_ingestor_ingestapi_ingest_proto_rawDescData
}

var file_pkg_ingestor_ingestapi_ingest_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pkg_ingestor_ingestapi_ingest_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_pkg_ingestor_ingestapi_ingest_proto_goTypes = []interface{}{
	(Status)(0),                    // 0: guacsec.guac.ingestor.schema.Status
	(*DocumentMetaData)(nil),       // 1: guacsec.guac.ingestor.schema.DocumentMetaData
	(*Document)(nil),               // 2: guacsec.guac.ingestor.schema.Document
	(*DocumentIngestRequest)(nil),  // 3: guacsec.guac.ingestor.schema.DocumentIngestRequest
	(*DocumentIngestResponse)(nil), // 4: guacsec.guac.ingestor.schema.DocumentIngestResponse
}
var file_pkg_ingestor_ingestapi_ingest_proto_depIdxs = []int32{
	1, // 0: guacsec.guac.ingestor.schema.DocumentIngestRequest.metadata:type_name -> guacsec.guac.ingestor.schema.DocumentMetaData
	2, // 1: guacsec.guac.ingestor.schema.DocumentIngestRequest.doc:type_name -> guacsec.guac.ingestor.schema.Document
	0, // 2: guacsec.guac.ingestor.schema.DocumentIngestResponse.status:type_name -> guacsec.guac.ingestor.schema.Status
	3, // 3: guacsec.guac.ingestor.schema.DocumentIngestService.IngestDocument:input_type -> guacsec.guac.ingestor.schema.DocumentIngestRequest
	4, // 4: guacsec.guac.ingestor.schema.DocumentIngestService.IngestDocument:output_type -> guacsec.guac.ingestor.schema.DocumentIngestResponse
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_pkg_ingestor_ingestapi_ingest_proto_init() }
func file_pkg_ingestor_ingestapi_ingest_proto_init() {
	if File_pkg_ingestor_ingestapi_ingest_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkg_ingestor_ingestapi_ingest_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DocumentMetaData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_ingestor_ingestapi_ingest_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Document); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_ingestor_ingestapi_ingest_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DocumentIngestRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_ingestor_ingestapi_ingest_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DocumentIngestResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_pkg_ingestor_ingestapi_ingest_proto_msgTypes[2].OneofWrappers = []interface{}{
		(*DocumentIngestRequest_Metadata)(nil),
		(*DocumentIngestRequest_Doc)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_ingestor_ingestapi_ingest_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_ingestor_ingestapi_ingest_proto_goTypes,
		DependencyIndexes: file_pkg_ingestor_ingestapi_ingest_proto_depIdxs,
		EnumInfos:         file_pkg_ingestor_ingestapi_ingest_proto_enumTypes,
		MessageInfos:      file_pkg_ingestor_ingestapi_ingest_proto_msgTypes,
	}.Build()
	File_pkg_ingestor_ingestapi_ingest_proto = out.File
	file_pkg_ingestor_ingestapi_ingest_proto_rawDesc = nil
	file_pkg_ingestor_ingestapi_ingest_proto_goTypes = nil
	file_pkg_ingestor_ingestapi_ingest_proto_depIdxs = nil
}
