FROM golang:1.19 as builder
ADD . /go/src/github.com/guacsec/guac/
WORKDIR /go/src/github.com/guacsec/guac/
RUN rm -rf bin/ && make build

FROM ubuntu:22.04
RUN apt update
RUN apt install -y ca-certificates
WORKDIR /root
COPY --from=builder /go/src/github.com/guacsec/guac/bin/ /opt/guac/
