FROM alpine:latest as certs
RUN apk --update add ca-certificates

FROM scratch

ENV PATH=/bin
COPY --from=certs /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/ca-certificates.crt

WORKDIR /guac
COPY guaccollect*  /opt/guac/guaccollect
COPY guaccsub*  /opt/guac/guaccsub
COPY guacgql*  /opt/guac/guacgql
COPY guacingest*  /opt/guac/guacingest
COPY guacone*  /opt/guac/guacone
