fragment allCertifyVEXStatementTree on CertifyVEXStatement {
  id
  subject {
    __typename
    ... on Package {
      id
      type
      namespaces {
        id
        namespace
        names {
          id
          name
          versions {
            id
            version
            qualifiers {
              key
              value
            }
            subpath
          }
        }
      }
    }
    ... on Artifact {
      id
      algorithm
      digest
    }
  }
  vulnerability {
    id
    type
    vulnerabilityIDs {
      id
      vulnerabilityID
    }
  }
  status
  vexJustification
  statement
  statusNotes
  knownSince
  origin
  collector
}

query CertifyVEXStatementQ1 {
  CertifyVEXStatement(certifyVEXStatementSpec: {}) {
    ...allCertifyVEXStatementTree
  }
}

query CertifyVEXStatementQ2 {
  CertifyVEXStatement(certifyVEXStatementSpec: { origin: "testing backend" }) {
    ...allCertifyVEXStatementTree
  }
}

query CertifyVEXStatementQ3 {
  CertifyVEXStatement(
    certifyVEXStatementSpec: { subject: { package: { name: "openssl" } } }
  ) {
    ...allCertifyVEXStatementTree
  }
}

query CertifyVEXStatementQ4 {
  CertifyVEXStatement(
    certifyVEXStatementSpec: {
      subject: {
        artifact: {
          algorithm: "sha256"
          digest: "6bbb0da1891646e58eb3e6a63af3a6fc3c8eb5a0d44824cba581d2e14a0450cf"
        }
      }
    }
  ) {
    ...allCertifyVEXStatementTree
  }
}

query CertifyVEXStatementQ5 {
  CertifyVEXStatement(
    certifyVEXStatementSpec: {
      vulnerability: { vulnerabilityID: "CVE-2019-13110" }
    }
  ) {
    ...allCertifyVEXStatementTree
  }
}

query CertifyVEXStatementQ6 {
  CertifyVEXStatement(
    certifyVEXStatementSpec: {
      vulnerability: { vulnerabilityID: "GHSA-h45f-rjvw-2rv2" }
    }
  ) {
    ...allCertifyVEXStatementTree
  }
}

query CertifyVEXStatementQ7 {
  CertifyVEXStatement(
    certifyVEXStatementSpec: {
      vulnerability: { vulnerabilityID: "CVE-2018-43610" }
    }
  ) {
    ...allCertifyVEXStatementTree
  }
}

query CertifyVEXStatementQ8 {
  CertifyVEXStatement(
    certifyVEXStatementSpec: {
      vulnerability: { vulnerabilityID: "GHSA-hj5f-4gvw-4rv2" }
    }
  ) {
    ...allCertifyVEXStatementTree
  }
}

query CertifyVEXStatementQ9 {
  CertifyVEXStatement(
    certifyVEXStatementSpec: {
      vulnerability: { vulnerabilityID: "cve-2019-14750" }
    }
  ) {
    ...allCertifyVEXStatementTree
  }
}

query CertifyVEXStatementQ10 {
  CertifyVEXStatement(
    certifyVEXStatementSpec: {
      vulnerability: { vulnerabilityID: "cve-2018-15710" }
    }
  ) {
    ...allCertifyVEXStatementTree
  }
}
