fragment allCertifyVEXStatement on CertifyVEXStatement {
  subject {
    __typename
    ... on Package {
      type
      namespaces {
        namespace
        names {
          name
          versions {
            version
            qualifiers {
              key
              value
            }
            subpath
          }
        }
      }
    }
    ... on Artifact {
      algorithm
      digest
    }
  }
  vulnerability {
    __typename
    ... on CVE {
      year
      cveIds {
        id
      }
    }
    ... on GHSA {
      ghsaIds {
        id
      }
    }
  }
  justification
  knownSince
  origin
  collector
}

query CertifyVEXStatementQ1 {
  CertifyVEXStatement(certifyVEXStatementSpec: {}) {
    ...allCertifyVEXStatement
  }
}

query CertifyVEXStatementQ2 {
  CertifyVEXStatement(certifyVEXStatementSpec: {origin: "testing backend"}) {
    ...allCertifyVEXStatement
  }
}

query CertifyVEXStatementQ3 {
  CertifyVEXStatement(certifyVEXStatementSpec: {subject: {package: {name: "openssl"}}}) {
    ...allCertifyVEXStatement
  }
}


query CertifyVEXStatementQ4 {
  CertifyVEXStatement(certifyVEXStatementSpec: {subject: {artifact: {algorithm: "sha256", digest: "6bbb0da1891646e58eb3e6a63af3a6fc3c8eb5a0d44824cba581d2e14a0450cf"}}}) {
    ...allCertifyVEXStatement
  }
}

query CertifyVEXStatementQ5 {
  CertifyVEXStatement(certifyVEXStatementSpec: {vulnerability: {cve: {cveId: "CVE-2019-13110"}}}) {
    ...allCertifyVEXStatement
  }
}

query CertifyVEXStatementQ6 {
  CertifyVEXStatement(certifyVEXStatementSpec: {vulnerability: {ghsa: {ghsaId: "GHSA-h45f-rjvw-2rv2"}}}) {
    ...allCertifyVEXStatement
  }
}

query CertifyVEXStatementQ7 {
  CertifyVEXStatement(certifyVEXStatementSpec: {vulnerability: {cve: {cveId: "CVE-2018-43610"}}}) {
    ...allCertifyVEXStatement
  }
}

query CertifyVEXStatementQ8 {
  CertifyVEXStatement(certifyVEXStatementSpec: {vulnerability: {ghsa: {ghsaId: "GHSA-hj5f-4gvw-4rv2"}}}) {
    ...allCertifyVEXStatement
  }
}
