fragment allCertifyBad on CertifyBad {
  justification
  subject {
    __typename
    ... on Package {
      type
      namespaces {
        namespace
        names {
          name
          versions {
            version
            qualifiers {
              key
              value
            }
            subpath
          }
        }
      }
    }
    ... on Source {
      type
      namespaces {
        namespace
        names {
          name
          tag
          commit
        }
      }
    }
    ... on Artifact {
      algorithm
      digest
    }
  }
  origin
  collector
}

query Q1 {
  CertifyBad(certifyBadSpec: {}) {
    ...allCertifyBad
  }
}

query Q2 {
  CertifyBad(certifyBadSpec: {origin: "testing backend"}) {
    ...allCertifyBad
  }
}

query Q3 {
  CertifyBad(certifyBadSpec: {package: {name: "openssl"}}) {
    ...allCertifyBad
  }
}

query Q4 {
  CertifyBad(certifyBadSpec: {source: {name: "github.com/guacsec/guac"}}) {
    ...allCertifyBad
  }
}

query Q5 {
  CertifyBad(certifyBadSpec: {artifact: {digest: "5a787865sd676dacb0142afa0b83029cd7befd9", algorithm: "sha1"}}) {
    ...allCertifyBad
  }
}

query Q6 {
  CertifyBad(
    certifyBadSpec: {package: {name: "openssl"}, source: {name: "github.com/guacsec/guac"}}
  ) {
    ...allCertifyBad
  }
}
