fragment allCertifyScorecardTree on CertifyScorecard {
  id
  source {
    ...allSrcTree
  }
  scorecard {
    timeScanned
    aggregateScore
    checks {
      check
      score
    }
    scorecardVersion
    scorecardCommit
    origin
    collector
  }
}

query ScorecardQ1 {
  scorecards(scorecardSpec: {}) {
    ...allCertifyScorecardTree
  }
}

query ScorecardQ2 {
  scorecards(scorecardSpec: {origin: "testing backend"}) {
    ...allCertifyScorecardTree
  }
}

query ScorecardQ3 {
  scorecards(scorecardSpec: {source: {name: "github.com/tensorflow/tensorflow"}}) {
    ...allCertifyScorecardTree
  }
}

query ScorecardQ4 {
  scorecards(
    scorecardSpec: {aggregateScore: 2.9}
  ) {
    ...allCertifyScorecardTree
  }
}

mutation Scorecard($source: SourceInputSpec!, $scorecard: ScorecardInputSpec!) {
  ingestSource(source: $source) {
    ...allSrcTree
  }
  certifyScorecard(source: $source, scorecard: $scorecard) {
    ...allCertifyScorecardTree
  }
}
