fragment allCertifyBadTree on CertifyBad {
  id
  justification
  knownSince
  subject {
    __typename
    ... on Package {
      id
      type
      namespaces {
        id
        namespace
        names {
          id
          name
          versions {
            id
            version
            qualifiers {
              key
              value
            }
            subpath
          }
        }
      }
    }
    ... on Source {
      id
      type
      namespaces {
        id
        namespace
        names {
          id
          name
          tag
          commit
        }
      }
    }
    ... on Artifact {
      id
      algorithm
      digest
    }
  }
  origin
  collector
}

query CertifactBadQ1 {
  CertifyBad(certifyBadSpec: {}) {
    ...allCertifyBadTree
  }
}

query CertifactBadQ2 {
  CertifyBad(certifyBadSpec: { origin: "testing backend" }) {
    ...allCertifyBadTree
  }
}

query CertifactBadQ3 {
  CertifyBad(certifyBadSpec: { subject: { package: { name: "openssl" } } }) {
    ...allCertifyBadTree
  }
}

query CertifactBadQ4 {
  CertifyBad(
    certifyBadSpec: { subject: { source: { name: "github.com/guacsec/guac" } } }
  ) {
    ...allCertifyBadTree
  }
}

query CertifactBadQ5 {
  CertifyBad(
    certifyBadSpec: {
      subject: {
        artifact: {
          digest: "6bbb0da1891646e58eb3e6a63af3a6fc3c8eb5a0d44824cba581d2e14a0450cf"
          algorithm: "sha256"
        }
      }
    }
  ) {
    ...allCertifyBadTree
  }
}

query CertifactBadQ6 {
  CertifyBad(
    certifyBadSpec: {
      subject: {
        package: { name: "openssl" }
        source: { name: "github.com/guacsec/guac" }
      }
    }
  ) {
    ...allCertifyBadTree
  }
}
