fragment allCertifyVulnTree on CertifyVuln {
  id
  package {
    id
    type
    namespaces {
      id
      namespace
      names {
        id
        name
        versions {
          id
          version
          qualifiers {
            key
            value
          }
          subpath
        }
      }
    }
  }
  vulnerability {
    id
    type
    vulnerabilityIDs {
      id
      vulnerabilityID
    }
  }
  metadata {
    dbUri
    dbVersion
    scannerUri
    scannerVersion
    timeScanned
    origin
    collector
  }
}

query CertifyVulnQ1 {
  CertifyVuln(certifyVulnSpec: {}) {
    ...allCertifyVulnTree
  }
}

query CertifyVulnQ2 {
  CertifyVuln(certifyVulnSpec: {origin: "testing backend"}) {
    ...allCertifyVulnTree
  }
}

query CertifyVulnQ3 {
  CertifyVuln(certifyVulnSpec: {package: {name: "openssl"}}) {
    ...allCertifyVulnTree
  }
}

query CertifyVulnQ4 {
  CertifyVuln(certifyVulnSpec: {package: {name: "django"}}) {
    ...allCertifyVulnTree
  }
}

query CertifyVulnQ5 {
  CertifyVuln(certifyVulnSpec: {vulnerability: {vulnerabilityID: "CVE-2019-13110"}}) {
    ...allCertifyVulnTree
  }
}

query CertifyVulnQ6 {
  CertifyVuln(
    certifyVulnSpec: {vulnerability: {vulnerabilityID: "GHSA-h45f-rjvw-2rv2"}}
  ) {
    ...allCertifyVulnTree
  }
}

query CertifyVulnQ7 {
  CertifyVuln(certifyVulnSpec: {vulnerability: {type: "osv", vulnerabilityID: "CVE-2019-13110"}}) {
    ...allCertifyVulnTree
  }
}

# Setting noVuln to true return all packages that have no vulnerabilities
# Setting noVuln to false return all packages with vulnerabilities
query CertifyNoVuln {
  CertifyVuln(certifyVulnSpec: {
    vulnerability: {noVuln: true}
  }) {
    ...allCertifyVulnTree
  }
}
