fragment allCertifyPkg on CertifyPkg {
  justification
  packages {
    type
    namespaces {
      namespace
      names {
        name
        versions {
          version
          qualifiers {
            key
            value
          }
          subpath
        }
      }
    }
  }
  origin
  collector
}

query Q1 {
  CertifyPkg(certifyPkgSpec: {}) {
    ...allCertifyPkg
  }
}

query Q2 {
  CertifyPkg(certifyPkgSpec: {origin: "Demo ingestion"}) {
    ...allCertifyPkg
  }
}

query Q3 {
  CertifyPkg(
    certifyPkgSpec: {packages: {type: "conan", namespace: "openssl.org", name: "openssl", version: "3.0.3", subpath: ""}}
  ) {
    ...allCertifyPkg
  }
}

query Q4 {
  CertifyPkg(
    certifyPkgSpec: {packages: {type: "pypi", namespace: "", name: "django", version: "1.11.1", subpath: "subpath"}}
  ) {
    ...allCertifyPkg
  }
}

query Q5 {
  CertifyPkg(
    certifyPkgSpec: {packages: {type: "deb", namespace: "debian"}}
  ) {
    ...allCertifyPkg
  }
}
