fragment allCertifyVulnTree on CertifyVuln {
  id
  package {
      id
      type
      namespaces {
        id
        namespace
        names {
          id
          name
          versions {
            id
            version
            qualifiers {
              key
              value
            }
            subpath
          }
        }
      }
    }
  vulnerability {
    __typename
    ... on CVE {
      id
      year
     cveIds{
      id
      cveId
    }
    }
    ... on OSV {
      id
     osvIds{
      id
      osvId
    }
    }
    ... on GHSA {
      id
      ghsaIds{
        id
        ghsaId
      }
    }
  }
  metadata {
    dbUri
    dbVersion
    scannerUri
    scannerVersion
    timeScanned
    origin
    collector
  }
}

query CertifyVulnQ1 {
  CertifyVuln(certifyVulnSpec: {}) {
    ...allCertifyVulnTree
  }
}

query CertifyVulnQ2 {
  CertifyVuln(certifyVulnSpec: {origin: "testing backend"}) {
    ...allCertifyVulnTree
  }
}

query CertifyVulnQ3 {
  CertifyVuln(certifyVulnSpec: {package: {name: "openssl"}}) {
    ...allCertifyVulnTree
  }
}

query CertifyVulnQ4 {
  CertifyVuln(certifyVulnSpec: {package: {name: "django"}}) {
    ...allCertifyVulnTree
  }
}

query CertifyVulnQ5 {
  CertifyVuln(certifyVulnSpec: {vulnerability: {cve: {cveId: "CVE-2019-13110"}}}) {
    ...allCertifyVulnTree
  }
}


query CertifyVulnQ6 {
  CertifyVuln(certifyVulnSpec: {vulnerability: {ghsa: {ghsaId: "GHSA-h45f-rjvw-2rv2"}}}) {
    ...allCertifyVulnTree
  }
}

query CertifyVulnQ7 {
  CertifyVuln(certifyVulnSpec: {vulnerability: {osv: {osvId: "CVE-2019-13110"}}}) {
    ...allCertifyVulnTree
  }
}
