fragment allCertifyBad on CertifyBad {
  justification
  subject {
    __typename
    ... on Package {
      type
      namespaces {
        namespace
        names {
          name
          versions {
            version
            qualifiers {
              key
              value
            }
            subpath
          }
        }
      }
    }
    ... on Source {
      type
      namespaces {
        namespace
        names {
          name
          tag
          commit
        }
      }
    }
    ... on Artifact {
      algorithm
      digest
    }
  }
  origin
  collector
}

query Q1 {
  CertifyBad(certifyBadSpec: {}) {
    ...allCertifyBad
  }
}

query Q2 {
  CertifyBad(certifyBadSpec: {origin: "testing backend"}) {
    ...allCertifyBad
  }
}

query Q3 {
  CertifyBad(certifyBadSpec: {subject: {package: {name: "openssl"}}}) {
    ...allCertifyBad
  }
}

query Q4 {
  CertifyBad(certifyBadSpec: {subject: {source: {name: "github.com/guacsec/guac"}}}) {
    ...allCertifyBad
  }
}

query Q5 {
  CertifyBad(certifyBadSpec: {subject: {artifact: {digest: "6bbb0da1891646e58eb3e6a63af3a6fc3c8eb5a0d44824cba581d2e14a0450cf", algorithm: "sha256"}}}) {
    ...allCertifyBad
  }
}

query Q6 {
  CertifyBad(
    certifyBadSpec: {subject: {package: {name: "openssl"}, source: {name: "github.com/guacsec/guac"}}}
  ) {
    ...allCertifyBad
  }
}
