fragment allCveTree on CVE {
  id
  year
  cveIds {
    id
    cveId
  }
}

fragment allGHSATree on GHSA {
  id
  ghsaIds {
    id
    ghsaId
  }
}

fragment allOSVTree on OSV {
  id
  osvIds {
    id
    osvId
  }
}

query CVEQ1 {
  cve(cveSpec: {}) {
    ...allCveTree
  }
}

query CVEQ2 {
  cve(cveSpec: {year: 2014}) {
    ...allCveTree
  }
}

query CVEQ3 {
  cve(cveSpec: {cveId: "CVE-2014-8139"}) {
    ...allCveTree
  }
}

query CVEQ4 {
  cve(cveSpec: {year: 2014, cveId: "CVE-2014-8140"}) {
    ...allCveTree
  }
}

mutation CVEM1 {
  ingestCVE(cve: {year: 2023, cveId: "CVE-2023-12345"}) {
    ...allCveTree
  }
}

mutation CVEM2 {
  ingestCVE(cve: {year: 2032, cveId: "cve-2032-12345"}) {
    ...allCveTree
  }
}

query GHSAQ1 {
  ghsa(ghsaSpec: {}) {
    ...allGHSATree
  }
}

query GHSAQ2 {
  ghsa(ghsaSpec: {ghsaId: "GHSA-h45f-rjvw-2rv2"}) {
    ...allGHSATree
  }
}

mutation GHSAM1 {
  ingestGHSA(ghsa: {ghsaId: "GHSA-abcd-efgh-1234"}) {
    ...allGHSATree
  }
}

query OSVQ1 {
  osv(osvSpec: {}) {
    ...allOSVTree
  }
}

query OSVQ2 {
  osv(osvSpec: {osvId: "CVE-2014-8139"}) {
    ...allOSVTree
  }
}

query OSVQ3 {
  osv(osvSpec: {osvId: "ghsa-h45f-rjvw-2rv2"}) {
    ...allOSVTree
  }
}

mutation OSVM1 {
  ingestOSV(osv: {osvId: "GHSA-abcd-efgh-1234"}) {
    ...allOSVTree
  }
}

mutation OSVM2 {
  ingestOSV(osv: {osvId: "CVE-2023-12345"}) {
    ...allOSVTree
  }
}
