fragment allHasSourceAtTree on HasSourceAt {
  id
  justification
  knownSince
  package {
    id
    type
    namespaces {
      id
      namespace
      names {
        id
        name
        versions {
          id
          version
          qualifiers {
            key
            value
          }
          subpath
        }
      }
    }
  }
  source {
    id
    type
    namespaces {
      id
      namespace
      names {
        id
        name
        tag
        commit
      }
    }
  }
  origin
  collector
}

query HasSourceAtQ1 {
  HasSourceAt(hasSourceAtSpec: {}) {
    ...allHasSourceAtTree
  }
}

query HasSourceAtQ2 {
  HasSourceAt(hasSourceAtSpec: {origin: "testing backend"}) {
    ...allHasSourceAtTree
  }
}

query HasSourceAtQ3 {
  HasSourceAt(hasSourceAtSpec: {package: {name: "openssl", version: "3.0.3"}})  {
    ...allHasSourceAtTree
  }
}

query HasSourceAtQ4 {
  HasSourceAt(
    hasSourceAtSpec: {source: {name: "https://github.com/django/django"}}
  ) {
    ...allHasSourceAtTree
  }
}

query HasSourceAtQ5 {
  HasSourceAt(hasSourceAtSpec: {package: {name: "kubetest"}}) {
    ...allHasSourceAtTree
  }
}

query HasSourceAtQ6 {
  HasSourceAt(
    hasSourceAtSpec: {source: {name: "https://github.com/vapor-ware/kubetest"}}
  ) {
    ...allHasSourceAtTree
  }
}
