fragment allHasSBOMTree on HasSBOM {
  uri
  subject {
    __typename
    ... on Package {
      type
      namespaces {
        namespace
        names {
          name
          versions {
            version
            qualifiers {
              key
              value
            }
            subpath
          }
        }
      }
    }
   ...on Source {
      type
      namespaces {
        namespace
        names {
          name
          tag
          commit
        }
      }
    }
  }
  origin
  collector
}

query HasSBOMQ1 {
  HasSBOM(hasSBOMSpec: {}) {
    ...allHasSBOMTree
  }
}

query HasSBOMQ2 {
  HasSBOM(hasSBOMSpec: {origin: "testing backend"}) {
    ...allHasSBOMTree
  }
}

query HasSBOMQ3 {
  HasSBOM(hasSBOMSpec: {subject: {package: {name: "openssl"}}}) {
    ...allHasSBOMTree
  }
}

query HasSBOMQ4 {
  HasSBOM(hasSBOMSpec: {subject: {source: {name: "github.com/guacsec/guac"}}}) {
    ...allHasSBOMTree
  }
}

query HasSBOMQ5 {
  HasSBOM(hasSBOMSpec: {subject: {package: {name: "openssl"}, source: {name: "github.com/guacsec/guac"}}}) {
    ...allHasSBOMTree
  }
}
