fragment allHasSLSATree on HasSLSA {
  id
  subject {
      id
      algorithm
      digest
  }
  slsa {
      builtFrom {
          id
          algorithm
          digest
      }
      builtBy {
        id
        uri
      }
      buildType
      slsaPredicate {
        key
        value
      }
      slsaVersion
      startedOn
      finishedOn
      origin
      collector
  }
}

query SLSAQ1 {
  HasSLSA(hasSLSASpec: {}) {
    ...allHasSLSATree
  }
}

query SLSAQ2 {
  HasSLSA(hasSLSASpec: {origin: "Demo ingestion"}) {
    ...allHasSLSATree
  }
}

query SLSAQ3 {
  HasSLSA(hasSLSASpec: {subject: {algorithm: "sha1"}}) {
    ...allHasSLSATree
  }
}

query SLSAQ4 {
  HasSLSA(hasSLSASpec: {builtFrom: [{algorithm: "sha256"}]}) {
    ...allHasSLSATree
  }
}

query SLSAQ5 {
  HasSLSA(hasSLSASpec: {id: "47"}) {
    ...allHasSLSATree
  }
}

query SLSAQ6 {
  HasSLSA(hasSLSASpec: {predicate: { key:"buildDefinition.externalParameters.ref", value:"refs/heads/main"}}) {
    ...allHasSLSATree
  }
}
