fragment allHasSBOMTree on HasSBOM {
  id
  uri
  annotation
  subject {
    __typename
    ... on Package {
      id
      type
      namespaces {
        id
        namespace
        names {
          id
          name
          versions {
            id
            version
            qualifiers {
              key
              value
            }
            subpath
          }
        }
      }
    }
   ...on Source {
      id
      type
      namespaces {
        id
        namespace
        names {
          id
          name
          tag
          commit
        }
      }
    }
  }
  origin
  collector
}

query HasSBOMQ1 {
  HasSBOM(hasSBOMSpec: {}) {
    ...allHasSBOMTree
  }
}

query HasSBOMQ2 {
  HasSBOM(hasSBOMSpec: {origin: "testing backend"}) {
    ...allHasSBOMTree
  }
}

query HasSBOMQ3 {
  HasSBOM(hasSBOMSpec: {subject: {package: {name: "openssl"}}}) {
    ...allHasSBOMTree
  }
}

query HasSBOMQ4 {
  HasSBOM(hasSBOMSpec: {subject: {source: {name: "github.com/guacsec/guac"}}}) {
    ...allHasSBOMTree
  }
}

query HasSBOMQ5 {
  HasSBOM(hasSBOMSpec: {subject: {package: {name: "openssl"}, source: {name: "github.com/guacsec/guac"}}}) {
    ...allHasSBOMTree
  }
}
