fragment allHasSourceAt on HasSourceAt {
  id
  justification
  knownSince
  package {
    id
    type
    namespaces {
      id
      namespace
      names {
        id
        name
        versions {
          id
          version
          qualifiers {
            key
            value
          }
          subpath
        }
      }
    }
  }
  source {
    id
    type
    namespaces {
      id
      namespace
      names {
        id
        name
        tag
        commit
      }
    }
  }
  origin
  collector
}

query Q1 {
  HasSourceAt(hasSourceAtSpec: {}) {
    ...allHasSourceAt
  }
}

query Q2 {
  HasSourceAt(hasSourceAtSpec: {origin: "testing backend"}) {
    ...allHasSourceAt
  }
}

# this will return nothing as we are not ingesting package openssl in testdata
query Q3 {
  HasSourceAt(hasSourceAtSpec: {package: {name: "openssl", version: "3.0.3"}})  {
    ...allHasSourceAt
  }
}

query Q4 {
  HasSourceAt(
    hasSourceAtSpec: {source: {name: "https://github.com/django/django"}}
  ) {
    ...allHasSourceAt
  }
}

query Q5 {
  HasSourceAt(hasSourceAtSpec: {package: {name: "kubetest"}}) {
    ...allHasSourceAt
  }
}

query Q6 {
  HasSourceAt(
    hasSourceAtSpec: {source: {name: "https://github.com/vapor-ware/kubetest"}}
  ) {
    ...allHasSourceAt
  }
}
