fragment allIsDependencyTree on IsDependency {
  id
  justification
  package {
    id
    type
    namespaces {
      id
      namespace
      names {
        id
        name
        versions {
          id
          version
          qualifiers {
            key
            value
          }
          subpath
        }
      }
    }
  }
  dependencyPackage {
    id
    type
    namespaces {
      id
      namespace
      names {
        id
        name
        versions {
          id
          version
          qualifiers {
            key
            value
          }
          subpath
        }
      }
    }
  }
  dependencyType
  versionRange
  origin
  collector
}

query IsDependencyQ1 {
  IsDependency(isDependencySpec: {}) {
    ...allIsDependencyTree
  }
}

query IsDependencyQ2 {
  IsDependency(isDependencySpec: { origin: "testing backend" }) {
    ...allIsDependencyTree
  }
}

query IsDependencyQ3 {
  IsDependency(isDependencySpec: { package: { name: "debian" } }) {
    ...allIsDependencyTree
  }
}

query IsDependencyQ4 {
  IsDependency(isDependencySpec: { package: { name: "dpkg" } }) {
    ...allIsDependencyTree
  }
}
# returns nothing as there is no package with openSSL. It is a dependent package
query IsDependencyQ5 {
  IsDependency(
    isDependencySpec: { package: { name: "openssl", version: "3.0.3" } }
  ) {
    ...allIsDependencyTree
  }
}

query IsDependencyQ6 {
  IsDependency(isDependencySpec: { dependentPackage: { name: "openssl" } }) {
    ...allIsDependencyTree
  }
}
