fragment allIsDependencyTree on IsDependency {
  id
  justification
  package {
    id
    type
    namespaces {
      id
      namespace
      names {
        id
        name
        versions {
          id
          version
          qualifiers {
            key
            value
          }
          subpath
        }
      }
    }
  }
dependentPackage {
    id
    type
    namespaces {
      id
      namespace
      names {
        id
        name
        versions {
          id
          version
          qualifiers {
            key
            value
          }
          subpath
        }
      }
    }
  }
versionRange
origin
collector
}

query Q1 {
  IsDependency(isDependencySpec: {}) {
    ...allIsDependencyTree
  }
}

query Q2 {
  IsDependency(isDependencySpec: {origin: "testing backend"}) {
    ...allIsDependencyTree
  }
}

query Q3 {
  IsDependency(isDependencySpec: {package: {name: "debian"}}) {
    ...allIsDependencyTree
  }
}

query Q4 {
  IsDependency(isDependencySpec: {package: {name: "dpkg"}}) {
    ...allIsDependencyTree
  }
}
# returns nothing as there is no package with openSSL. It is a dependent package
query Q5 {
  IsDependency(isDependencySpec: {package: {name: "openssl", version: "3.0.3"}}) {
    ...allIsDependencyTree
  }
}

query Q6 {
  IsDependency(isDependencySpec: {dependentPackage: {name: "openssl"}}) {
    ...allIsDependencyTree
  }
}
