fragment allIsOccurrencesTree on IsOccurrence {
  subject {
    __typename
    ... on Package {
      type
      namespaces {
        namespace
        names {
          name
          versions {
            version
            qualifiers {
              key
              value
            }
            subpath
          }
        }
      }
    }
   ...on Source {
      type
      namespaces {
        namespace
        names {
          name
          tag
          commit
        }
      }
    }
  }
  artifact {
    algorithm
    digest
  }
  justification
  origin
  collector
}

query Q1 {
  IsOccurrence(isOccurrenceSpec: {}) {
    ...allIsOccurrencesTree
  }
}

query Q2 {
  IsOccurrence(isOccurrenceSpec: {origin: "testing backend"}) {
    ...allIsOccurrencesTree
  }
}

query Q3 {
  IsOccurrence(isOccurrenceSpec: {subject: {package: {name: "openssl"}}}) {
    ...allIsOccurrencesTree
  }
}

query Q4 {
  IsOccurrence(isOccurrenceSpec: {subject: {package: {name: "openssl", version: "3.0.3"}}}) {
    ...allIsOccurrencesTree
  }
}

query Q5 {
  IsOccurrence(isOccurrenceSpec: {subject: {source: {name: "github.com/guacsec/guac"}}}) {
    ...allIsOccurrencesTree
  }
}

query Q6 {
  IsOccurrence(
    isOccurrenceSpec: {subject: {package: {name: "openssl"}, source: {name: "github.com/guacsec/guac"}}}
  ) {
    ...allIsOccurrencesTree
  }
}
