fragment allIsOccurrencesTree on IsOccurrence {
  id
  subject {
    __typename
    ... on Package {
      id
      type
      namespaces {
        id
        namespace
        names {
          id
          name
          versions {
            id
            version
            qualifiers {
              key
              value
            }
            subpath
          }
        }
      }
    }
   ...on Source {
      id
      type
      namespaces {
        id
        namespace
        names {
          id
          name
          tag
          commit
        }
      }
    }
  }
  artifact {
    id
    algorithm
    digest
  }
  justification
  origin
  collector
}

query IsOccurrenceQ1 {
  IsOccurrence(isOccurrenceSpec: {}) {
    ...allIsOccurrencesTree
  }
}

query IsOccurrenceQ2 {
  IsOccurrence(isOccurrenceSpec: {origin: "testing backend"}) {
    ...allIsOccurrencesTree
  }
}

query IsOccurrenceQ3 {
  IsOccurrence(isOccurrenceSpec: {subject: {package: {name: "openssl"}}}) {
    ...allIsOccurrencesTree
  }
}

query IsOccurrenceQ4 {
  IsOccurrence(isOccurrenceSpec: {subject: {package: {name: "openssl", version: "3.0.3"}}}) {
    ...allIsOccurrencesTree
  }
}

query IsOccurrenceQ5 {
  IsOccurrence(isOccurrenceSpec: {subject: {source: {name: "github.com/guacsec/guac"}}}) {
    ...allIsOccurrencesTree
  }
}

query IsOccurrenceQ6 {
  IsOccurrence(
    isOccurrenceSpec: {subject: {package: {name: "openssl"}, source: {name: "github.com/guacsec/guac"}}}
  ) {
    ...allIsOccurrencesTree
  }
}
