fragment allPkgTree on Package {
  type
  namespaces {
    namespace
    names {
      name
      versions {
        version
        qualifiers {
          key
          value
        }
        subpath
      }
    }
  }
}

mutation PkgM1 {
  ingestPackage(pkg: {type: "pypi", name: "tensorflow"}) {
    ...allPkgTree
  }
}

query PkgQ1 {
  packages(pkgSpec: {}) {
    ...allPkgTree
  }
}
