fragment allPkgTree on Package {
  id
  type
  namespaces {
    id
    namespace
    names {
      id
      name
      versions {
        id
        version
        qualifiers {
          key
          value
        }
        subpath
      }
    }
  }
}

query PkgQ1 {
  packages(pkgSpec: {}) {
    type
    namespaces {
      namespace
      names {
        name
      }
    }
  }
}

# all packages
query PkgQ2 {
  packages(pkgSpec: {}) {
    ...allPkgTree
  }
}

# only PyPI packages
query PkgQ3 {
  packages(pkgSpec: { type: "pypi" }) {
    ...allPkgTree
  }
}

# PyPI packages in "debian" namespace (empty)
query PkgQ4 {
  packages(pkgSpec: { type: "pypi", namespace: "debian" }) {
    ...allPkgTree
  }
}

# debian packages in "debian" namespace
query PkgQ5 {
  packages(pkgSpec: { type: "deb", namespace: "debian" }) {
    ...allPkgTree
  }
}

# "dpkg" package from Ubuntu ("ubuntu" namespace on "deb" type)
query PkgQ6 {
  packages(pkgSpec: { type: "deb", namespace: "ubuntu", name: "dpkg" }) {
    ...allPkgTree
  }
}

# All "deb" type packages named "dpkg"
query PkgQ7 {
  packages(pkgSpec: { type: "deb", name: "dpkg" }) {
    ...allPkgTree
  }
}

# All occurrences of openssl-3.0.3
query PkgQ8 {
  packages(pkgSpec: { name: "openssl", version: "3.0.3" }) {
    ...allPkgTree
  }
}

# All occurrences of openssl
query PkgQ9 {
  packages(pkgSpec: { name: "openssl" }) {
    ...allPkgTree
  }
}

query PkgQA {
  packages(pkgSpec: { qualifiers: [{ key: "arch", value: "amd64" }] }) {
    ...allPkgTree
  }
}

query PkgQB {
  packages(
    pkgSpec: {
      qualifiers: [
        { key: "arch", value: "amd64" }
        { key: "distro", value: "stretch" }
      ]
    }
  ) {
    ...allPkgTree
  }
}

query PkgQC {
  packages(pkgSpec: { subpath: "subpath" }) {
    ...allPkgTree
  }
}

query PkgQD {
  packages(pkgSpec: { matchOnlyEmptyQualifiers: true }) {
    ...allPkgTree
  }
}

fragment allPkgIDs on PackageIDs {
  packageTypeID
  packageNamespaceID
  packageNameID
  packageVersionID
}

mutation PkgM1 {
  ingestPackage(pkg: { type: "pypi", name: "tensorflow" }) {
    ...allPkgIDs
  }
}

mutation PkgM2 {
  ingestPackage(
    pkg: {
      type: "pypi"
      name: "tensorflow"
      qualifiers: [
        { key: "arch", value: "amd64" }
        { key: "distro", value: "stretch" }
      ]
    }
  ) {
    ...allPkgIDs
  }
}

mutation PkgM3 {
  ingestPackage(pkg: { type: "pypi", name: "tensorflow", version: "2.12.0" }) {
    ...allPkgIDs
  }
}

mutation PkgM4 {
  ingestPackage(
    pkg: {
      type: "pypi"
      name: "tensorflow"
      version: "2.12.0"
      qualifiers: [
        { key: "arch", value: "amd64" }
        { key: "distro", value: "stretch" }
      ]
    }
  ) {
    ...allPkgIDs
  }
}

mutation PkgM5 {
  ingestPackage(
    pkg: {
      type: "pypi"
      name: "tensorflow"
      version: "2.12.0"
      qualifiers: [
        { key: "distro", value: "stretch" }
        { key: "arch", value: "amd64" }
      ]
    }
  ) {
    ...allPkgIDs
  }
}

mutation PkgM6 {
  ingestPackage(
    pkg: {
      type: "pypi"
      name: "tensorflow"
      version: "2.12.0"
      subpath: "foo"
      qualifiers: [
        { key: "distro", value: "stretch" }
        { key: "arch", value: "amd64" }
      ]
    }
  ) {
    ...allPkgIDs
  }
}

mutation PkgM7 {
  ingestPackage(
    pkg: {
      type: "pypi"
      name: "tensorflow"
      version: "2.12.0"
      subpath: "foo"
      qualifiers: [
        { key: "distro", value: "stretch" }
        { key: "arch", value: "amd64" }
      ]
    }
  ) {
    ...allPkgIDs
  }
}
