fragment allSrcTree on Source {
  type
  namespaces {
    namespace
    names {
      name
      tag
      commit
    }
  }
}

query Q1 {
  sources(sourceSpec: {name: "github.com/guacsec/guac"}) {
    ...allSrcTree
  }
}

query Q2 {
  sources(sourceSpec: {qualifier: {tag: "v0.0.1"}}) {
    ...allSrcTree
  }
}

query Q3 {
  sources(
    sourceSpec: {qualifier: {commit: "fcba958b73e27cad8b5c8655d46439984d27853b"}}
  ) {
    ...allSrcTree
  }
}

query Q4 {
  sources(sourceSpec: {qualifier: {}}) {
    ...allSrcTree
  }
}

query Q5 {
  sources(sourceSpec: {type: "svn"}) {
    ...allSrcTree
  }
}

query Q6 {
  sources(sourceSpec: {namespace: "gitlab"}) {
    ...allSrcTree
  }
}

query Q7 {
  sources(sourceSpec: {}) {
    ...allSrcTree
  }
}

query Q8 {
  sources(sourceSpec: {qualifier: {tag: "asd", commit: "sad"}}) {
    ...allSrcTree
  }
}
