fragment allSrcTree on Source {
  type
  namespaces {
    namespace
    names {
      name
      tag
      commit
    }
  }
}

query SrcQ1 {
  sources(sourceSpec: {}) {
    namespaces {
      names {
        name
      }
    }
  }
}

query SrcQ2 {
  sources(sourceSpec: {}) {
    ...allSrcTree
  }
}

# Return only sources with neither tag nor commit
query SrcQ3 {
  sources(sourceSpec: {tag:"", commit:""}) {
    ...allSrcTree
  }
}


query SrcQ4 {
  sources(sourceSpec: {name: "github.com/guacsec/guac"}) {
    ...allSrcTree
  }
}

query SrcQ5 {
  sources(sourceSpec: {tag: "v0.0.1"}) {
    ...allSrcTree
  }
}

query SrcQ6 {
  sources(
    sourceSpec: {commit: "fcba958b73e27cad8b5c8655d46439984d27853b"}
  ) {
    ...allSrcTree
  }
}
query SrcQ7 {
  sources(sourceSpec: {type: "svn"}) {
    ...allSrcTree
  }
}

query SrcQ8 {
  sources(sourceSpec: {namespace: "gitlab"}) {
    ...allSrcTree
  }
}

# this should error as both `tag` and `commit` are specified and not empty
query SrcQ9 {
  sources(sourceSpec: {tag: "asd", commit: "sad"}) {
    ...allSrcTree
  }
}
