query GetPkg ($spec: PkgSpec) {
  packages(pkgSpec: $spec){
    ...allPkgTree
  }
}

query GetSrc  ($spec: SourceSpec) {
  sources(sourceSpec: $spec){
    ...allSrcTree
  }
}

query GetArtifact ($spec: ArtifactSpec) {
  artifacts(artifactSpec: $spec){
    ...allArtifactTree
  }
}

query GetCve ($spec: CVESpec) {
    cve(cveSpec: $spec) {
        ...allCveTree
    }
}

query GetIsDepedency($spec: IsDependencySpec) {
  IsDependency(isDependencySpec: $spec){
      ...allIsDependencyTree
  }
}

query GetIsOccurrence($spec: IsOccurrenceSpec) {
  IsOccurrence(isOccurrenceSpec: $spec){
      ...allIsOccurrencesTree
  }
}

query GetHasSourceAt($spec: HasSourceAtSpec) {
  HasSourceAt(hasSourceAtSpec: $spec){
      ...allHasSourceAtTree
  }
}

query GetCertifyVuln($spec: CertifyVulnSpec) {
  CertifyVuln(certifyVulnSpec: $spec){
      ...allCertifyVulnTree
  }
}

query ReachQ1 {
  packages(pkgSpec: {
    type:"deb",
    namespace:"ubuntu",
    name: "dpkg",
    qualifiers: [{key:"arch", value:"amd64"}],
  }) {
    ...allPkgTree
  }
}
